import type { UsageItem } from "./model"

// Connect an integration: 29 items in 2 areas (specs/15-connect-integration.md). Baseline numbers describe Meridian Software.
// Halyard overrides: the agency connects a client's CRM whenever a client is onboarded, so the wizard is routine there.
// Fathom overrides: no CRM at all (PLAN.md, 13 Sep 2026 — Ollopa is Fathom's CRM); a calendar and an enrichment
// provider are the whole list. Only "sdr" and "admin" roles exist there.
// Ridgeline overrides: HubSpot, a calendar, Slack and enrichment; little outbound, so Slack is about deals and agents.
// Non-admin roles reach the wizard only to connect their own calendar.
// Plan gating (PLAN.md, 13 Sep 2026): CRM sync is one-way on Starter, two-way on Growth, two-way plus custom objects
// on Scale; webhooks and API keys are Growth and above. Every lock sits on the card or the row at the entry point,
// never after the admin has mapped fields or built a condition (gated-features pattern rule 7).

export const connectItems: UsageItem[] = [
  // Wizard
  { id: "wiz.choose", page: "connect", area: "Wizard", label: "Choose what to connect", weekly: { sdr: 4, ae: 5, marketer: 1, cs: 4, admin: 5 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 }, ridgeline: { admin: 3 } }, note: "Non-admins connect their own calendar only. Halyard connects a client CRM most months." },
  { id: "wiz.declare-no-crm", page: "connect", area: "Wizard", label: "Ollopa is our CRM: a declarable answer on the CRM group", weekly: { admin: 3 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 2 }, ridgeline: { admin: 1 } }, note: "Declaring it takes the CRM row out of Home's set-up list and empties the list at Fathom, so the door goes rather than nagging for ever. Reversible from the same place. A permanent to-do for a decision already made is a door onto nothing (rule 4)." },
  { id: "wiz.sf-permissions", page: "connect", area: "Wizard", label: "What the sync user must be able to do, above the sign-in button", critical: true, weekly: { admin: 2 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 5 }, ridgeline: { admin: 0 } }, note: "Create, read and edit on Accounts, Contacts, Leads, Opportunities and User Roles, plus API Enabled under System Permissions; Salesforce Essentials cannot connect. A requirement discovered after the consent screen is a requirement discovered too late (rule 7)." },
  { id: "wiz.authorise", page: "connect", area: "Wizard", label: "Authorise (sign in, key, test event)", weekly: { sdr: 4, ae: 5, marketer: 1, cs: 4, admin: 6 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 }, ridgeline: { admin: 3 } } },
  { id: "wiz.sandbox", page: "connect", area: "Wizard", label: "Salesforce: production or sandbox", weekly: { admin: 2 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 4 }, ridgeline: { admin: 0 } }, note: "Fathom and Ridgeline have no Salesforce." },
  { id: "wiz.objects", page: "connect", area: "Wizard", label: "Choose what syncs (objects and direction)", weekly: { admin: 5 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 }, ridgeline: { admin: 3 } } },
  { id: "wiz.mapping", page: "connect", area: "Wizard", label: "Map fields (pairs and write rule)", weekly: { admin: 5 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 22 }, ridgeline: { admin: 3 } }, note: "The write rule sits in the pair's row; never on another step (rule 5)." },
  { id: "wiz.suggested-mappings", page: "connect", area: "Wizard", label: "Pre-mapped rows marked suggested, counted in the tab label, and confirmed by saving the step", weekly: { admin: 5 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 22 }, ridgeline: { admin: 3 } }, note: "\"Contacts \u00b7 14 mapped, 9 suggested, 1 required unmapped\". A guess presented as a decision is the thing rule 6 objects to: the state is declared, saving confirms it and says so, and editing one marks it edited." },
  { id: "wiz.no-approval-events", page: "connect", area: "Wizard", label: "Approvals are not webhook events, and where they do arrive", critical: true, weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 1 }, ridgeline: { admin: 6 } }, note: "One line on the webhook event list. A surface with no reply path cannot carry a decision, and an auto-approver has zero review capacity (rule 7's corollary). Slack carries approval notifications because a Slack message carries a link." },
  { id: "wiz.stage-mapping", page: "connect", area: "Wizard", label: "Map stages", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 12 }, ridgeline: { admin: 2 } }, note: "Only when deals sync." },
  { id: "wiz.pull-conditions", page: "connect", area: "Wizard", label: "Pull conditions", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 15 }, ridgeline: { admin: 2 } } },
  { id: "wiz.push-conditions", page: "connect", area: "Wizard", label: "Push conditions, unverified emails, source value", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 15 }, ridgeline: { admin: 2 } } },
  { id: "wiz.deletion", page: "connect", area: "Wizard", label: "Deletion behaviour", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 10 }, ridgeline: { admin: 2 } }, note: "What a mirrored deletion does to the CRM is a destructive consequence (rule 7)." },
  { id: "wiz.merge", page: "connect", area: "Wizard", label: "Merge behaviour", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 10 }, ridgeline: { admin: 2 } }, note: "A mirrored merge changes the system of record (rule 7)." },
  { id: "wiz.matching-key", page: "connect", area: "Wizard", label: "Matching key for duplicates", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 5 }, ridgeline: { admin: 2 } } },
  { id: "wiz.review", page: "connect", area: "Wizard", label: "Review, consequence statement, start syncing", critical: true, weekly: { admin: 5 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 }, ridgeline: { admin: 3 } }, note: "States what the first sync will pull, push, delete and merge. Nothing syncs until this button (rule 7)." },
  { id: "wiz.save-exit", page: "connect", area: "Wizard", label: "Save and exit, resume, discard", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 8 }, ridgeline: { admin: 2 } } },
  { id: "wiz.slack-channels", page: "connect", area: "Wizard", label: "Slack: events to channels", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 3 }, ridgeline: { admin: 4 } } },
  { id: "wiz.calendar-pick", page: "connect", area: "Wizard", label: "Calendar: which calendars, busy time only", weekly: { sdr: 4, ae: 5, marketer: 1, cs: 4, admin: 2 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 2 }, ridgeline: { admin: 2 } } },
  { id: "wiz.enrichment", page: "connect", area: "Wizard", label: "Enrichment provider: key, fields, order", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } } },
  { id: "wiz.webhook", page: "connect", area: "Wizard", label: "Webhook: URL, secret, events, test", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } }, note: "Fathom's founder would build her own automations, but webhooks start at Growth: the card carries the lock, the plan and the price, and she has opened it once." },
  { id: "wiz.custom-objects", page: "connect", area: "Wizard", label: "Custom CRM objects", weekly: { admin: 3 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 2 }, ridgeline: { admin: 1 } }, note: "Scale only. The lock sits in step 3's object list, where the objects are chosen, so nobody maps fields for an object they cannot sync (gated-features pattern rule 7). Removed at Fathom, which has no CRM." },
  { id: "wiz.template", page: "connect", area: "Wizard", label: "Save as or start from a setup template", weekly: { admin: 1 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 22 }, ridgeline: { admin: 0 } }, note: "Halyard's accelerator (rule 8): the same CRM choices, ten times over." },

  // Integration page
  { id: "int.handover", page: "connect", area: "Integration page", label: "Where the wizard hands over, named by kind", weekly: { admin: 4 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 10 }, ridgeline: { admin: 4 } }, note: "A CRM, a calendar, Slack and an enrichment provider hand over to this page; a webhook hands over to Settings \u203a API, webhooks, MCP and CLI \u203a the subscription, where the delivery contract lives. One object, one container (rule 5)." },
  { id: "int.status", page: "connect", area: "Integration page", label: "Status, last and next sync, records today, errors today", critical: true, weekly: { sdr: 3, ae: 3, cs: 2, admin: 40 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 }, ridgeline: { admin: 30 } }, note: "Matches Settings item int.crm. Sync state is safety state (rule 7)." },
  { id: "int.errors", page: "connect", area: "Integration page", label: "Errors grouped by cause, largest group first, each with a count and a one-line cause", weekly: { admin: 30 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 25 }, ridgeline: { admin: 25 } }, note: "Matches Settings item int.error-log. Shown at level one when errors exist (object state). Grouped rather than flat and newest-first, because 340 rows of one cause is one decision, not 340: a group expands in place to its records, and the date and object filters stay as a control. The same treatment a failing webhook subscription gets \u2014 one pattern, two places." },
  { id: "int.retry", page: "connect", area: "Integration page", label: "Retry a group, with its count and how it batches", weekly: { admin: 20 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 18 }, ridgeline: { admin: 15 } }, note: "\"Retry 340 duplicate errors \u00b7 100 at a time, about 4 passes\". A retry that says neither how many nor how long is an action with no consequence line, and the group count after the run is the confirmation." },
  { id: "int.pause", page: "connect", area: "Integration page", label: "Pause or resume syncing", critical: true, weekly: { admin: 5 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 3 } }, note: "Safety state (rule 7)." },
  { id: "int.edit-mapping", page: "connect", area: "Integration page", label: "Edit field mapping in place", weekly: { admin: 15 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 10 }, ridgeline: { admin: 10 } }, note: "Matches Settings item int.field-mapping. Never through the wizard." },
  { id: "int.mapping-consequence", page: "connect", area: "Integration page", label: "What removing or retyping an existing pair does, stated at the pair before Save", critical: true, weekly: { admin: 8 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 8 }, ridgeline: { admin: 6 } }, note: "\"Removing this pair can stop Contacts syncing until the next full pull. Run a full pull after saving?\" \u2014 with the pull offered there. Editing a mapping is the most destructive thing on this page and it used to have an applies-to line and no warning (rule 7)." },
  { id: "int.apply-mapping", page: "connect", area: "Integration page", label: "Apply mapping to existing records", weekly: { admin: 8 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 6 }, ridgeline: { admin: 5 } } },
  { id: "int.pull-push-now", page: "connect", area: "Integration page", label: "Pull now, push now", weekly: { admin: 20 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 12 }, ridgeline: { admin: 12 } }, note: "After a CRM field change or a stuck record." },
  { id: "int.edit-rules", page: "connect", area: "Integration page", label: "Edit sync rules in place", weekly: { admin: 6 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 6 }, ridgeline: { admin: 4 } } },
  { id: "int.reauthorise", page: "connect", area: "Integration page", label: "Re-authorise, change sync user", weekly: { sdr: 2, ae: 2, cs: 2, admin: 5 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 4 }, ridgeline: { admin: 4 } }, note: "Tokens and passwords expire." },
  { id: "int.history", page: "connect", area: "Integration page", label: "Sync history", weekly: { admin: 20 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 8 }, ridgeline: { admin: 12 } } },
  { id: "int.disconnect", page: "connect", area: "Integration page", label: "Disconnect, with what happens", critical: true, weekly: { admin: 1 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 1 } }, note: "The path to disconnect is as short as the path to connect (rule 7)." },
]
