import type { UsageItem } from "./model"

// Developer surfaces: the API, webhooks, MCP and the CLI, plus the four panels that configure them
// (`X-key`, `X-hook`, `X-mcpscope`, `X-cliauth`) and the approval card that arrives where there is no
// screen (`X-approve-remote`). Spec: specs/17-developer-surfaces.md. Nodes: IA-MAP 2.16.
//
// The settings *rows* for this area — "API keys", "Webhooks", "MCP connection and scope", "CLI device
// authorisations" and the three published commitments — live in usage/settings.ts under the area
// "API, webhooks, MCP and CLI", because they are rows of the Settings page and count in its shape.
// This file holds what the surfaces themselves carry.
//
// Seats: OPS for the workspace rows; the MCP scope row and the CLI authorisations are personal, so the
// SDR seat has numbers too (IA-MAP 2.14, corrected seats cell). No AE, marketer or CS numbers: those
// seats never reach a key, a hook or a terminal, and an item with no number for a role is not on their
// page at all.
//
// Baseline describes Meridian: one nightly enrichment job on one key, read weekly.
// Fathom (Starter, founder holds OPS and SDR) lives in an AI client every day, so MCP read scope — which
// is on every plan (IA-MAP 6.4f) — carries the page there, and the two write tiers sit locked and priced.
// Halyard (Growth) is the CLI's reason for existing: ten client workspaces, one loop, every week.
// Ridgeline (Growth) is event-driven: the webhook subscription is the surface they watch.

export const developerItems: UsageItem[] = [
  // API keys and limits (X-key, and the area above the key list)
  { id: "api.key-list", page: "developer", area: "API keys and limits", label: "API keys with scope, last used and spend per key", weekly: { admin: 25 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 20 }, ridgeline: { admin: 12 } }, note: "Locked on Starter, so the row and its price are on Fathom's page and the number says how often the founder looks at it rather than what she could do with it (gated-features pattern rule 9)." },
  { id: "api.key-create", page: "developer", area: "API keys and limits", label: "Create a key: name, scope, expiry", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 8 }, ridgeline: { admin: 2 } } },
  { id: "api.key-scope", page: "developer", area: "API keys and limits", label: "What a key may reach, and whether it reaches restricted records", weekly: { admin: 8 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 10 }, ridgeline: { admin: 4 } }, note: "O8's compliance sweep asks one question of a key: does it reach the removal list. The scope answers it here rather than in a policy page." },
  { id: "api.key-spend", page: "developer", area: "API keys and limits", label: "Spend per key, against the workspace balance", critical: true, weekly: { admin: 30 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 35 }, ridgeline: { admin: 15 } }, note: "Price attribution for the person paying (rule 7). A key that spends and cannot say what it spent is the complaint the product exists to answer." },
  { id: "api.key-rotate", page: "developer", area: "API keys and limits", label: "Rotate or revoke a key", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 6 }, ridgeline: { admin: 2 } } },
  { id: "api.limits", page: "developer", area: "API keys and limits", label: "Limits are per workspace, not per key: 200 a minute, 6,000 an hour, 50,000 a day", critical: true, weekly: { admin: 20 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 18 }, ridgeline: { admin: 8 } }, note: "Published where keys are made, because a developer who does not know the limit is per workspace mints three (19§9: 'Every limit is: per team, not per API key or per user')." },
  { id: "api.cost-table", page: "developer", area: "API keys and limits", label: "Published cost per endpoint: typical and maximum, with the waterfall tail", critical: true, weekly: { admin: 6 }, overrides: { fathom: { admin: 22 }, halyard: { admin: 20 }, ridgeline: { admin: 4 } }, note: "The maximum, not the average: one phone waterfall reaches 45+ credits (19§9). An average hides a 45x outcome, which is the partitioned-pricing error rule 7 cites." },
  { id: "api.alert-80", page: "developer", area: "API keys and limits", label: "Alert the key's owner at 80% of the allocation", critical: true, weekly: { admin: 4 }, overrides: { fathom: { admin: 20 }, halyard: { admin: 14 }, ridgeline: { admin: 3 } }, note: "On by default. Delivered as a digest line and a bell row under the existing 'credits low' kind; no new notification kind." },
  { id: "api.key-jobs", page: "developer", area: "API keys and limits", label: "The enrichment jobs this key ran", weekly: { admin: 20 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 15 }, ridgeline: { admin: 6 } }, note: "The route from a key to what caused its spend. Opens the job record filtered to that key." },

  // The API (U-api): the commitments that arrive in a response rather than on a screen
  { id: "api.credit-header", page: "developer", area: "The API", label: "Credits remaining beside requests remaining, on every credit-consuming response", critical: true, weekly: { admin: 22 }, overrides: { fathom: { admin: 25 }, halyard: { admin: 18 }, ridgeline: { admin: 8 } }, note: "A rate limit is not a budget. A nightly job that stops when it runs out of requests still burns credits until it does." },
  { id: "api.cap-refusal", page: "developer", area: "The API", label: "At the cap: a refusal naming the cap, the reset and the approver, never a partial result", critical: true, weekly: { admin: 5 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 8 }, ridgeline: { admin: 2 } } },
  { id: "api.pending-approval", page: "developer", area: "The API", label: "A write over the second-approval threshold returns the pending-approval object with its consequence, cost and approver", critical: true, weekly: { admin: 6 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 12 }, ridgeline: { admin: 2 } }, note: "The same item appears in the app's queue and is decided once (PLAN.md, 14 Sep 2026)." },
  { id: "api.unowned", page: "developer", area: "The API", label: "An object the key's owner does not own: readable fields and an owner line", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 6 }, ridgeline: { admin: 1 } } },
  { id: "api.no-area", page: "developer", area: "The API", label: "An area the key's seat does not hold: a refusal naming the seats and the admin", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 1 } } },
  { id: "api.no-profile", page: "developer", area: "The API", label: "Profile omission does not exist for a key, and the document says so", weekly: { admin: 1 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 1 } }, note: "The third shape of 'cannot see it' stated rather than left to inference: an integrator who is not told invents an answer." },
  { id: "api.cursor", page: "developer", area: "The API", label: "Cursor paging, and the cursor the nightly reconciliation walks", weekly: { admin: 8 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 10 } } },
  { id: "api.errors", page: "developer", area: "The API", label: "The error shapes a caller must handle", weekly: { admin: 6 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 3 }, ridgeline: { admin: 4 } } },

  // Webhooks (U-hooks, X-hook)
  { id: "hook.list", page: "developer", area: "Webhooks", label: "Webhook subscriptions: URL, events, state", weekly: { admin: 6 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 25 } }, note: "Locked on Starter. Ridgeline is event-driven, so the subscription list is the surface they watch." },
  { id: "hook.state", page: "developer", area: "Webhooks", label: "This subscription's state: delivering, failing since, or paused by you", critical: true, weekly: { admin: 20 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 35 } }, note: "Not the receiver's uptime: the subscription's own state. Calendly disables a subscription after one undelivered message and it has to be recreated (19§10), which is exactly the silent failure this row exists to make loud." },
  { id: "hook.contract", page: "developer", area: "Webhooks", label: "The delivery contract: at-least-once, signed, attempt-numbered, retried for 24 hours, never silently disabled", critical: true, weekly: { admin: 5 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 18 } }, note: "What a thing does to your data is never behind a door (rule 7). Outreach does not retry on a 500 with a five-second timeout, so a 500 from your handler is permanent data loss (19§10); a developer who cannot read the contract builds the wrong handler and finds out by losing data." },
  { id: "hook.events", page: "developer", area: "Webhooks", label: "Which events this subscription carries, and that approvals are not among them", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 12 } }, note: "A webhook fires on what happened, never on what needs deciding: a surface with no reply path cannot carry a decision, and an auto-approver has zero review capacity (rule 7's corollary)." },
  { id: "hook.log", page: "developer", area: "Webhooks", label: "Delivery log, grouped by cause", weekly: { admin: 6 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 30 } }, note: "The same grouped-by-cause treatment the sync error panel gives CRM errors. One pattern, two places." },
  { id: "hook.replay", page: "developer", area: "Webhooks", label: "Replay the failures in one group", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 15 } } },
  { id: "hook.reconcile", page: "developer", area: "Webhooks", label: "The reconciliation endpoint, named and copyable", critical: true, weekly: { admin: 6 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 20 } }, note: "Delivery is neither guaranteed nor ordered, so the nightly cursor walk is mandatory (19§9 pattern D). An endpoint that is required and unnamed is a promise the product does not keep." },
  { id: "hook.secret", page: "developer", area: "Webhooks", label: "Signing secret, and rotating it", weekly: { admin: 1 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 1 }, ridgeline: { admin: 4 } } },
  { id: "hook.digest", page: "developer", area: "Webhooks", label: "A failing subscription in the daily digest, with its failure count and cause", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 20 } }, note: "Digestible, not interrupting: a webhook failing for an hour is not a safety state, and the three interrupting bell kinds stay three." },

  // MCP (U-mcp, X-mcpscope)
  { id: "mcp.tiers", page: "developer", area: "MCP", label: "Three scopes: read, safe writes, destructive writes", critical: true, weekly: { admin: 20, sdr: 2 }, overrides: { fathom: { admin: 30, sdr: 30 }, halyard: { admin: 6, sdr: 4 }, ridgeline: { admin: 4 } }, note: "Read scope is on every plan; the two write tiers ride the API entitlement at Growth and above (IA-MAP 6.4f)." },
  { id: "mcp.actions", page: "developer", area: "MCP", label: "Each action inside the chosen tier: allowed, approval-required or blocked", weekly: { admin: 6, sdr: 2 }, overrides: { fathom: { admin: 25, sdr: 25 }, halyard: { admin: 4, sdr: 3 }, ridgeline: { admin: 3 } } },
  { id: "mcp.ceiling", page: "developer", area: "MCP", label: "The ceiling that applies: your own limit, or the workspace cap and what is left of it", critical: true, weekly: { admin: 5, sdr: 3 }, overrides: { fathom: { admin: 35, sdr: 35 }, halyard: { admin: 5, sdr: 4 }, ridgeline: { admin: 3 } }, note: "At Fathom no seat carries a personal limit, so the client inherits the workspace cap; a ceiling nobody states is the surprise at the end of the month (rule 7)." },
  { id: "mcp.training", page: "developer", area: "MCP", label: "Where this workspace stands on model training, stated at connection", critical: true, weekly: { admin: 2, sdr: 1 }, overrides: { fathom: { admin: 10, sdr: 10 }, halyard: { admin: 2, sdr: 2 }, ridgeline: { admin: 2 } }, note: "How data is used is named in rule 7 explicitly, so it is a line at connection time, not a policy page." },
  { id: "mcp.turn-batch", page: "developer", area: "MCP", label: "One approval card at the end of the client's turn, carrying the total and each item's consequence", critical: true, weekly: { admin: 6, sdr: 3 }, overrides: { fathom: { admin: 40, sdr: 40 }, halyard: { admin: 4, sdr: 4 }, ridgeline: { admin: 2 } }, note: "The turn is the boundary. One card per tool call is the step-by-step queue rule 7's corollary measures: 88.5% seen, 23.9% stopped (Chen et al., n=48)." },
  { id: "mcp.tool-credits", page: "developer", area: "MCP", label: "Remaining credits on every credit-consuming tool result, and a refusal rather than a partial write at the cap", critical: true, weekly: { admin: 4, sdr: 3 }, overrides: { fathom: { admin: 35, sdr: 35 }, halyard: { admin: 4, sdr: 4 }, ridgeline: { admin: 2 } }, note: "A partial result is what a model summarises as success." },
  { id: "mcp.tool-list", page: "developer", area: "MCP", label: "The tool list is exactly the seat's areas; no profile filtering, and the connection document says so", weekly: { admin: 2, sdr: 1 }, overrides: { fathom: { admin: 8, sdr: 8 }, halyard: { admin: 2, sdr: 2 }, ridgeline: { admin: 1 } } },
  { id: "mcp.devices", page: "developer", area: "MCP", label: "Your MCP connections: client, authorised when, revoke", weekly: { admin: 4, sdr: 2 }, overrides: { fathom: { admin: 15, sdr: 15 }, halyard: { admin: 4, sdr: 3 }, ridgeline: { admin: 2 } } },
  { id: "mcp.write-lock", page: "developer", area: "MCP", label: "The lock on the two write tiers, with the plan name and the monthly total", critical: true, weekly: { admin: 2, sdr: 1 }, overrides: { fathom: { admin: 20, sdr: 20 }, halyard: { admin: 1, sdr: 1 }, ridgeline: { admin: 1 } }, note: "At the tier, before any work exists, and restated by the endpoint at connection — never at the moment a write fails (gated-features pattern rule 7)." },

  // The CLI (U-cli, X-cliauth)
  { id: "cli.devices", page: "developer", area: "The CLI", label: "CLI device authorisations: workspace, last used, revoke", weekly: { admin: 3 }, overrides: { fathom: { admin: 6, sdr: 4 }, halyard: { admin: 20, sdr: 12 }, ridgeline: { admin: 2 } }, note: "Browser sign-in, and a device flow where there is no browser." },
  { id: "cli.workspace", page: "developer", area: "The CLI", label: "Every command takes a workspace, and the workspace name is echoed in every confirmation", critical: true, weekly: { admin: 6 }, overrides: { fathom: { admin: 4, sdr: 3 }, halyard: { admin: 45, sdr: 20 }, ridgeline: { admin: 2 } }, note: "Ten workspaces, one loop, weekly: the wrong workspace is the only failure mode that matters here." },
  { id: "cli.typed-back", page: "developer", area: "The CLI", label: "A destructive bulk write asks for the workspace name typed back", critical: true, weekly: { admin: 2 }, overrides: { fathom: { admin: 2, sdr: 1 }, halyard: { admin: 30, sdr: 10 }, ridgeline: { admin: 1 } }, note: "The pattern Delete workspace already uses in Settings. One pattern, two places." },
  { id: "cli.preflight", page: "developer", area: "The CLI", label: "Before a bulk write: what changes, how many records, how many credits, and the allocation checked first", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 3, sdr: 2 }, halyard: { admin: 40, sdr: 15 }, ridgeline: { admin: 2 } }, note: "The same three facts the app prints, checked before the run rather than failing halfway." },
  { id: "cli.exit-codes", page: "developer", area: "The CLI", label: "Published exit codes: 0 ok, 1 error, 2 usage, 3 permission, 4 rate limited, 5 over the credit cap, 6 awaiting approval", critical: true, weekly: { admin: 2 }, overrides: { fathom: { admin: 2, sdr: 1 }, halyard: { admin: 25, sdr: 8 }, ridgeline: { admin: 1 } }, note: "A script cannot branch on prose. The states a caller must handle are the terminal's version of safety state (rule 7)." },
  { id: "cli.resume", page: "developer", area: "The CLI", label: "Resume a bulk run from its token", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 30, sdr: 10 }, ridgeline: { admin: 1 } }, note: "Printed on exit code 6, so an approval continues the run rather than restarting it." },
  { id: "cli.export", page: "developer", area: "The CLI", label: "Export a table this seat can already read", weekly: { admin: 4 }, overrides: { fathom: { admin: 3, sdr: 2 }, halyard: { admin: 35, sdr: 12 }, ridgeline: { admin: 2 } }, note: "Exporting a table a seat can already read is on every plan; exporting a report is Growth; scheduled delivery is Scale. One rule, owned by the plan table in spec 14." },
  { id: "cli.unowned", page: "developer", area: "The CLI", label: "A record you do not own exports its readable fields with an owner column", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 12, sdr: 5 }, ridgeline: { admin: 1 } } },
  { id: "cli.no-area", page: "developer", area: "The CLI", label: "An area your seat does not hold exits 3, naming the seats that hold it and the admin to ask", weekly: { admin: 1 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 8, sdr: 4 }, ridgeline: { admin: 1 } }, note: "Profile omission does not apply in a terminal, and `--help` says so: three shapes, no fourth answer." },
  { id: "cli.locked", page: "developer", area: "The CLI", label: "A locked capability prints the plan name and the monthly total, not a 403", weekly: { admin: 2 }, overrides: { fathom: { admin: 8, sdr: 6 }, halyard: { admin: 4, sdr: 2 }, ridgeline: { admin: 1 } } },

  // The approval card where there is no screen (X-approve-remote)
  { id: "rem.card", page: "developer", area: "The approval card", label: "The card: actor, consequence sentence, recipients or record, credit cost, second-approval line", critical: true, weekly: { admin: 6, sdr: 2 }, overrides: { fathom: { admin: 30, sdr: 30 }, halyard: { admin: 15, sdr: 10 }, ridgeline: { admin: 2 } }, note: "Not summarisable and not collapsible: the card is what the model may not paraphrase away." },
  { id: "rem.decide-once", page: "developer", area: "The approval card", label: "The same item is in the app's queue and is decided once, in either place", critical: true, weekly: { admin: 3, sdr: 2 }, overrides: { fathom: { admin: 20, sdr: 20 }, halyard: { admin: 10, sdr: 6 }, ridgeline: { admin: 2 } } },
  { id: "rem.bulk-one-item", page: "developer", area: "The approval card", label: "A bulk write from a surface is one item, owned by whoever ran it, with the count, the total consequence and the total credits", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 4, sdr: 3 }, halyard: { admin: 20, sdr: 8 }, ridgeline: { admin: 1 } }, note: "Four thousand queue items is rule 7's corollary written as a screen. The records are reachable from the count." },
  { id: "rem.ledger-surface", page: "developer", area: "The approval card", label: "The run in the ledger, with the surface marked and the human named first", weekly: { admin: 4, sdr: 2 }, overrides: { fathom: { admin: 25, sdr: 20 }, halyard: { admin: 15, sdr: 6 }, ridgeline: { admin: 3 } }, note: "'Priya Natarajan · Claude (MCP)': the authorisation is the human's, and the ledger is what the compliance answer is read from." },
]
