import type { UsageItem } from "./model"

// Import and enrichment: the import wizard (`W-import`), the reveal panel (`X-enrich`), the enrichment
// job record (`R-job`) and the job-change sweep that re-prospects a mover.
// Spec: specs/18-import-and-enrichment.md. Nodes: IA-MAP 2.15.
//
// Seats: SDR, marketer and admin. No AE and no CS numbers: neither seat imports a file or buys a phone
// number, and an item with no number for a role is not on their page at all.
//
// Baseline describes Meridian, where a list is imported every few weeks and revealing is a routine part
// of building a sequence. Halyard carries the page: client lists arrive weekly, one workspace at a time,
// which is why a saved column mapping — rare everywhere else — is the agency's most-used control.
// Fathom reveals daily and the credits are the founders' own money, so every price line is read every time.
// Ridgeline barely imports; what they do here is the monthly job-change sweep, which is the best lead
// a product-led business gets.

export const enrichmentItems: UsageItem[] = [
  // The import wizard (W-import): five steps, one door each at most
  { id: "imp.entry", page: "enrichment", area: "The import wizard", label: "Reached from People, Companies and Lists, from ⌘K, and by deep link; the header offers 'Add to sidebar'", weekly: { sdr: 8, marketer: 5, admin: 4 }, overrides: { halyard: { sdr: 18, admin: 18 }, fathom: { admin: 8, sdr: 6 }, ridgeline: { sdr: 3, marketer: 3, admin: 3 } }, note: "A page, not a drawer: five stages, a trial run, a spend and a resume is an independent task (rule 5's container guidance), and the map makes it a level-1 node." },
  { id: "imp.file", page: "enrichment", area: "The import wizard", label: "The file, and its columns matched to fields with three rows previewed", weekly: { sdr: 20, marketer: 8, admin: 5 }, overrides: { halyard: { sdr: 55, admin: 55 }, fathom: { admin: 18, sdr: 15 }, ridgeline: { sdr: 5, marketer: 4, admin: 3 } } },
  { id: "imp.saved-mapping", page: "enrichment", area: "The import wizard", label: "Save this column mapping for this client, and reuse it next time", weekly: { sdr: 3, marketer: 2, admin: 2 }, overrides: { halyard: { sdr: 45, admin: 45 }, fathom: { admin: 2, sdr: 2 }, ridgeline: { sdr: 2, marketer: 1, admin: 1 } }, note: "Rule 1 read per business rather than per product: rare at Meridian, the agency's most-used control on this page." },
  { id: "imp.duplicates", page: "enrichment", area: "The import wizard", label: "Duplicates: update existing, skip, or create anyway — each with the records it changes and whose they are", critical: true, weekly: { sdr: 18, marketer: 8, admin: 6 }, overrides: { halyard: { sdr: 30, admin: 30 }, fathom: { admin: 15, sdr: 12 }, ridgeline: { sdr: 4, marketer: 3, admin: 3 } }, note: "'Update existing' overwrites fields on records other people own, and the sentence says how many and that their owner does not change (rule 7)." },
  { id: "imp.owner", page: "enrichment", area: "The import wizard", label: "Owner and list for the new rows", weekly: { sdr: 15, marketer: 7, admin: 4 }, overrides: { halyard: { sdr: 25, admin: 25 }, fathom: { admin: 12, sdr: 10 }, ridgeline: { sdr: 4, marketer: 3, admin: 2 } } },
  { id: "imp.fields", page: "enrichment", area: "The import wizard", label: "Which fields enrichment may fill", weekly: { sdr: 14, marketer: 8, admin: 5 }, overrides: { halyard: { sdr: 15, admin: 15 }, fathom: { admin: 15, sdr: 12 }, ridgeline: { sdr: 4, marketer: 4, admin: 3 } } },
  { id: "imp.provider-order", page: "enrichment", area: "The import wizard", label: "The provider lineup, with the workspace default named and where it is set", weekly: { sdr: 8, marketer: 4, admin: 12 }, overrides: { halyard: { sdr: 12, admin: 14 }, fathom: { admin: 18, sdr: 14 }, ridgeline: { sdr: 3, marketer: 2, admin: 5 } }, note: "Declared, and shown beside where it came from (Settings › Pipeline and data › Enrichment provider order), or the same decision gets made twice with two answers (rules 5 and 6)." },
  { id: "imp.stop-rule", page: "enrichment", area: "The import wizard", label: "Stop at the first verified result, or continue down the waterfall", critical: true, weekly: { sdr: 8, marketer: 3, admin: 6 }, overrides: { halyard: { sdr: 10, admin: 12 }, fathom: { admin: 16, sdr: 14 }, ridgeline: { sdr: 3, marketer: 2, admin: 3 } }, note: "This one radio is the difference between 8 credits and 45 on a phone waterfall (19§9), so it is a price control, not a preference." },
  { id: "imp.row-ceiling", page: "enrichment", area: "The import wizard", label: "The most this run may spend on one row", critical: true, weekly: { sdr: 8, marketer: 3, admin: 6 }, overrides: { halyard: { sdr: 12, admin: 14 }, fathom: { admin: 25, sdr: 20 }, ridgeline: { sdr: 3, marketer: 2, admin: 3 } } },
  { id: "imp.trial", page: "enrichment", area: "The import wizard", label: "The ten-row trial: hit rate by field, credits spent, cost per hit, and the projected total for the file", critical: true, weekly: { sdr: 20, marketer: 8, admin: 6 }, overrides: { halyard: { sdr: 40, admin: 40 }, fathom: { admin: 30, sdr: 24 }, ridgeline: { sdr: 4, marketer: 3, admin: 3 } }, note: "The price disclosure of this page. The projected total is printed before the button that spends it, never after (rule 7)." },
  { id: "imp.run", page: "enrichment", area: "The import wizard", label: "Progress, a stop control, and the line that says the run survives a closed tab", weekly: { sdr: 16, marketer: 6, admin: 4 }, overrides: { halyard: { sdr: 45, admin: 45 }, fathom: { admin: 12, sdr: 10 }, ridgeline: { sdr: 4, marketer: 3, admin: 2 } }, note: "The wizard ends on the job record, never on a toast." },

  // Reveal and enrich (X-enrich), opened from a selection
  { id: "enr.choice", page: "enrichment", area: "Reveal and enrich", label: "What to reveal: verified email, or email and mobile", critical: true, weekly: { sdr: 35, marketer: 10, admin: 4 }, overrides: { fathom: { admin: 75, sdr: 70 }, halyard: { sdr: 15, admin: 12 }, ridgeline: { sdr: 8, marketer: 4, admin: 2 } }, note: "Two prices, one choice: a phone costs about four times an email, so the choice is made where the price is shown." },
  { id: "enr.estimate", page: "enrichment", area: "Reveal and enrich", label: "The per-row estimate, the total for the selection, and the balance after", critical: true, weekly: { sdr: 35, marketer: 10, admin: 4 }, overrides: { fathom: { admin: 75, sdr: 70 }, halyard: { sdr: 15, admin: 12 }, ridgeline: { sdr: 8, marketer: 4, admin: 2 } } },
  { id: "enr.dnc-line", page: "enrichment", area: "Reveal and enrich", label: "How many of the selection carry a do-not-call flag, that a mobile for those is charged and cannot be called, and that they are excluded unless you include them", critical: true, weekly: { sdr: 30, marketer: 6, admin: 4 }, overrides: { fathom: { admin: 65, sdr: 60 }, halyard: { sdr: 12, admin: 10 }, ridgeline: { sdr: 6, marketer: 3, admin: 2 } }, note: "The flag and the spend are weighed together, so they are never on opposite sides of a door (rule 5); the charge is not refunded, so it is stated before the click (rule 7)." },
  { id: "enr.single-row", page: "enrichment", area: "Reveal and enrich", label: "The single-row reveal keeps its one click and its price on the control", weekly: { sdr: 45, marketer: 8, admin: 4 }, overrides: { fathom: { admin: 80, sdr: 75 }, halyard: { sdr: 18, admin: 12 }, ridgeline: { sdr: 10, marketer: 4, admin: 2 } }, note: "The panel is for a selection; one row is one price on one button, and the accelerator is not taken away." },
  { id: "enr.restricted", page: "enrichment", area: "Reveal and enrich", label: "A restricted person keeps their row and their place in the count, with the action replaced by the rule that restricts them", weekly: { sdr: 4, marketer: 3, admin: 8 }, overrides: { fathom: { admin: 4, sdr: 3 }, halyard: { sdr: 4, admin: 6 }, ridgeline: { sdr: 4, marketer: 3, admin: 5 } }, note: "'Restricted: EU region rule · Prospecting rules'. Never silently filtered: a silently shortened count is the worst version of a gap that does not explain itself." },

  // The job report (R-job)
  { id: "job.header", page: "enrichment", area: "The job report", label: "Source, fields, provider order, rows, matched, credits and cost per hit", critical: true, weekly: { sdr: 22, marketer: 8, admin: 22 }, overrides: { halyard: { sdr: 45, admin: 45 }, fathom: { admin: 35, sdr: 28 }, ridgeline: { sdr: 5, marketer: 4, admin: 5 } }, note: "Cost per hit is the number the next run is designed from, so it is in the header and not computed by the reader." },
  { id: "job.by-field", page: "enrichment", area: "The job report", label: "The report by field: what landed, what did not, and from which provider", weekly: { sdr: 14, marketer: 7, admin: 14 }, overrides: { halyard: { sdr: 25, admin: 25 }, fathom: { admin: 18, sdr: 16 }, ridgeline: { sdr: 4, marketer: 3, admin: 4 } } },
  { id: "job.unmatched", page: "enrichment", area: "The job report", label: "The unmatched rows, and 'Drop these from the list'", weekly: { sdr: 12, marketer: 5, admin: 12 }, overrides: { halyard: { sdr: 30, admin: 30 }, fathom: { admin: 18, sdr: 15 }, ridgeline: { sdr: 4, marketer: 3, admin: 4 } } },
  { id: "job.status-landing", page: "enrichment", area: "The job report", label: "Email verification status landing after the run", weekly: { sdr: 12, marketer: 4, admin: 8 }, overrides: { halyard: { sdr: 15, admin: 15 }, fathom: { admin: 30, sdr: 25 }, ridgeline: { sdr: 4, marketer: 2, admin: 3 } } },
  { id: "job.all-rows", page: "enrichment", area: "The job report", label: "All rows · n", weekly: { sdr: 6, marketer: 3, admin: 6 }, overrides: { halyard: { sdr: 10, admin: 10 }, fathom: { admin: 8, sdr: 6 }, ridgeline: { sdr: 2, marketer: 2, admin: 2 } }, note: "The record's one door: long content nobody reads alongside the report." },
  { id: "job.from-elsewhere", page: "enrichment", area: "The job report", label: "The same job reached from an API key, from Prospecting rules or from the credit breakdown", weekly: { sdr: 3, marketer: 2, admin: 10 }, overrides: { halyard: { sdr: 4, admin: 14 }, fathom: { admin: 8, sdr: 4 }, ridgeline: { sdr: 2, marketer: 2, admin: 5 } }, note: "One record, four parents. A key that spends has to lead to what it spent on." },
  { id: "job.rerun", page: "enrichment", area: "The job report", label: "Run the unmatched rows again with a different provider order, priced before the button", weekly: { sdr: 4, marketer: 2, admin: 6 }, overrides: { halyard: { sdr: 10, admin: 10 }, fathom: { admin: 8, sdr: 6 }, ridgeline: { sdr: 2, marketer: 1, admin: 2 } } },

  // Job changes and re-prospecting
  { id: "move.signal", page: "enrichment", area: "Job changes", label: "The job-change signal: what fired, when, and from where", weekly: { sdr: 5, marketer: 4, admin: 3 }, overrides: { ridgeline: { sdr: 35, marketer: 20, admin: 8 }, fathom: { admin: 3, sdr: 3 }, halyard: { sdr: 3, admin: 3 } }, note: "A former user at a new employer is the best lead a product-led business gets, which is why Ridgeline carries this area." },
  { id: "move.confirm", page: "enrichment", area: "Job changes", label: "Job change · confirm and update: update this record, or create a new contact, each with what it keeps", critical: true, weekly: { sdr: 4, marketer: 3, admin: 3 }, overrides: { ridgeline: { sdr: 30, marketer: 12, admin: 6 }, fathom: { admin: 3, sdr: 3 }, halyard: { sdr: 3, admin: 2 } }, note: "Merge existed and its opposite did not. Updating keeps one timeline and loses the old employer's context; creating keeps both and splits the history. Both consequences are written before the choice." },
  { id: "move.employer", page: "enrichment", area: "Job changes", label: "Whether the new employer is already an account, who owns it, and how many open deals it has", critical: true, weekly: { sdr: 4, marketer: 3, admin: 3 }, overrides: { ridgeline: { sdr: 30, marketer: 12, admin: 6 }, fathom: { admin: 3, sdr: 3 }, halyard: { sdr: 3, admin: 2 } }, note: "The answer decides whether this is a fresh prospect or somebody else's account, and the decision is made on the contact, so the answer sits on the contact (rule 5)." },
  { id: "move.old-email", page: "enrichment", area: "Job changes", label: "The old address and its bounce state, beside the new one", weekly: { sdr: 3, marketer: 2, admin: 2 }, overrides: { ridgeline: { sdr: 25, marketer: 8, admin: 5 }, fathom: { admin: 2, sdr: 2 }, halyard: { sdr: 2, admin: 2 } } },
  { id: "move.enrol", page: "enrichment", area: "Job changes", label: "Enrol the mover in the warm sequence, with the net-new count and what it costs", weekly: { sdr: 3, marketer: 2, admin: 2 }, overrides: { ridgeline: { sdr: 20, marketer: 8, admin: 4 }, fathom: { admin: 2, sdr: 2 }, halyard: { sdr: 2, admin: 2 } } },
  // The tail a real import page accumulates: the format questions a file raises once, the run's own
  // housekeeping, and the fee fact that has to be written down even though almost nobody reads it twice.
  { id: "imp.encoding", page: "enrichment", area: "The import wizard", label: "Character encoding and delimiter, when a file will not parse", weekly: { sdr: 4, marketer: 2, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 2, sdr: 2 }, ridgeline: { sdr: 1, marketer: 1, admin: 1 } } },
  { id: "imp.date-format", page: "enrichment", area: "The import wizard", label: "Date and number formats in this file", weekly: { sdr: 3, marketer: 2, admin: 2 }, overrides: { halyard: { sdr: 3, admin: 3 }, fathom: { admin: 2, sdr: 1 }, ridgeline: { sdr: 1, marketer: 1, admin: 1 } } },
  { id: "imp.phone-region", page: "enrichment", area: "The import wizard", label: "Default country for phone numbers that do not carry one", weekly: { sdr: 3, marketer: 2, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 2, sdr: 2 }, ridgeline: { sdr: 1, marketer: 1, admin: 1 } } },
  { id: "imp.skip-blank", page: "enrichment", area: "The import wizard", label: "Rows with no email: skip them, or import them and enrich", weekly: { sdr: 4, marketer: 3, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 3, sdr: 3 }, ridgeline: { sdr: 1, marketer: 1, admin: 1 } } },
  { id: "imp.notify", page: "enrichment", area: "The import wizard", label: "Tell me when the run finishes", weekly: { sdr: 4, marketer: 2, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 2, sdr: 2 }, ridgeline: { sdr: 1, marketer: 1, admin: 1 } } },
  { id: "imp.schedule", page: "enrichment", area: "The import wizard", label: "Repeat this import on a schedule", weekly: { sdr: 2, marketer: 2, admin: 3 }, overrides: { halyard: { sdr: 3, admin: 3 }, fathom: { admin: 2, sdr: 1 }, ridgeline: { sdr: 1, marketer: 1, admin: 2 } } },
  { id: "imp.history", page: "enrichment", area: "The import wizard", label: "Past imports, and the job each one produced", weekly: { sdr: 4, marketer: 3, admin: 5 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 4, sdr: 3 }, ridgeline: { sdr: 2, marketer: 2, admin: 2 } } },
  { id: "job.export", page: "enrichment", area: "The job report", label: "Export the job report", weekly: { sdr: 3, marketer: 2, admin: 4 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 3, sdr: 2 }, ridgeline: { sdr: 1, marketer: 1, admin: 2 } }, note: "Exporting a table a seat can already read is on every plan (spec 14's plan table owns that rule)." },
  { id: "job.charging", page: "enrichment", area: "The job report", label: "What was charged and what was not: a row that returned nothing is not charged, and a match that returns a number nobody may call is", critical: true, weekly: { sdr: 4, marketer: 2, admin: 6 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 15, sdr: 12 }, ridgeline: { sdr: 2, marketer: 1, admin: 3 } }, note: "A fee statement, so it is on the record rather than in a help article, whatever its number (rule 7). Nothing here is refunded, and the sentence says so." },
  { id: "enr.columns", page: "enrichment", area: "Reveal and enrich", label: "Which revealed fields become columns on the table afterwards", weekly: { sdr: 4, marketer: 3, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 }, fathom: { admin: 4, sdr: 4 }, ridgeline: { sdr: 2, marketer: 2, admin: 1 } } },
]
