import type { UsageItem } from "./model"

// Reports: five fixed reports (Activity, Pipeline, Sequences, Campaign results, Forecast) with one date range and one team filter.
// Spec: specs/12-reports.md. Baseline numbers describe Meridian Software. The SDR has no Reports entry, so no sdr numbers.
// Fathom overrides: only the founder (admin) uses it; no campaigns and no teams, so those items are 0 and removed from the page.
// Halyard overrides: the ops lead (admin) produces the client report weekly, so print and sequence detail are routine.
// Ridgeline overrides: product-led; pipeline is renewals and expansion, campaigns are lifecycle, sequences are nearly idle.
// Plan gating (PLAN.md, 13 Sep 2026, plan table): Starter gets the Activity report only; Growth gets all five plus CSV
// export; Scale adds the scheduled weekly email. Exporting a table a seat can already read is on every plan; exporting a
// report is Growth; scheduled delivery is Scale — one rule, owned by spec 14's plan table and rendered here.
// The Forecast tab is on every plan for the seats that hold it: a submitted forecast is a commitment, and decision-critical
// items are never gated (gated-features pattern rule 6). On Starter the number and the goal show and the team roll-up,
// which needs teams, is locked.
// `ae_plus` numbers describe an AE seat with direct reports (IA-MAP 6.4j). No business declares a sixth seat. A lock does not change a number (gated-features pattern rule 9): the item stays where
// its weekly use puts it and carries the lock and the plan name. Fathom is on Starter, Halyard and Ridgeline on Growth,
// Meridian on Scale.

export const reportsItems: UsageItem[] = [
  // Reports
  { id: "rep.overview", page: "reports", area: "Reports", label: "Overview strip", weekly: { ae: 45, marketer: 55, cs: 30, admin: 60 }, overrides: { fathom: { admin: 55 }, halyard: { admin: 70 }, ridgeline: { ae: 35, marketer: 60, cs: 45, admin: 50 } }, note: "The page visit itself: the tile row of every report the role uses." },
  { id: "rep.activity", page: "reports", area: "Reports", label: "Activity report", weekly: { ae: 8, marketer: 12, cs: 10, admin: 45 }, overrides: { fathom: { admin: 55 }, halyard: { admin: 65 }, ridgeline: { cs: 20, admin: 30 } }, note: "The one report Starter includes, which is why Fathom's founder reads it most weeks." },
  { id: "rep.pipeline", page: "reports", area: "Reports", label: "Pipeline report", weekly: { ae: 45, marketer: 10, cs: 22, admin: 40 }, overrides: { fathom: { admin: 8 }, halyard: { admin: 15 }, ridgeline: { ae: 35, cs: 40 } }, note: "Ridgeline renewals are deals, so CS lives here. Halyard's own pipeline is small; clients' pipelines are not in ollopA. Locked on Starter: Fathom's founder reads the board on Deals instead and comes here for the forecast tile, which shows on every plan." },
  { id: "rep.sequences", page: "reports", area: "Reports", label: "Sequences report", weekly: { ae: 4, marketer: 4, cs: 1, admin: 25 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 65 }, ridgeline: { admin: 4, marketer: 2 } }, note: "Locked on Starter; the bounce tile shows anyway, and per-sequence numbers are on Sequences." },
  { id: "rep.campaigns", page: "reports", area: "Reports", label: "Campaign results", weekly: { ae: 2, marketer: 55, cs: 4, admin: 12 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 60, cs: 12, admin: 22 } }, note: "Removed, not disabled, where the business has no campaigns." },

  // Controls
  { id: "ctl.range", page: "reports", area: "Controls", label: "Date range presets", weekly: { ae: 35, marketer: 50, cs: 22, admin: 55 }, overrides: { fathom: { admin: 50 }, halyard: { admin: 65 } } },
  { id: "ctl.month", page: "reports", area: "Controls", label: "This month and Last month", weekly: { ae: 15, ae_plus: 18, marketer: 18, cs: 12, admin: 18 }, overrides: { halyard: { admin: 40 }, fathom: { admin: 22 }, ridgeline: { marketer: 18, cs: 12, admin: 15 } }, note: "A monthly quota period is read on a monthly range; the preset list had quarters and weeks and nothing in between." },
  { id: "ctl.custom-range", page: "reports", area: "Controls", label: "Custom date range", weekly: { ae: 4, marketer: 12, cs: 3, admin: 8 }, overrides: { halyard: { admin: 18 } }, note: "Inside the date-range menu. Halyard matches client billing periods." },
  { id: "ctl.team", page: "reports", area: "Controls", label: "Team filter", weekly: { ae: 10, ae_plus: 55, marketer: 18, cs: 6, admin: 40 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { admin: 30 } }, note: "Removed where there are no teams. A scoped AE sees a sentence naming the admin instead; an AE with direct reports gets a working control fixed to her own team, because scope is her whole reason for being on this page." },
  { id: "ctl.person", page: "reports", area: "Controls", label: "Person filter", weekly: { ae: 15, ae_plus: 40, marketer: 4, cs: 12, admin: 18 }, overrides: { fathom: { admin: 35 }, halyard: { admin: 50 } }, note: "Inside the team menu, beneath the team list. Small teams look at people." },
  { id: "ctl.compare", page: "reports", area: "Controls", label: "Compare with previous period", weekly: { ae: 15, marketer: 30, cs: 8, admin: 15 }, overrides: { ridgeline: { marketer: 35 } }, note: "Depends on the range, so it lives in the date-range menu when under 20 (rule 5)." },
  { id: "ctl.export-csv", page: "reports", area: "Controls", label: "Export CSV", weekly: { ae: 6, marketer: 22, cs: 5, admin: 25 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 45 }, ridgeline: { marketer: 25 } }, note: "Growth and above (PLAN.md plan table). Halyard is on Growth, so the weekly client report leaves as a CSV and the number says so; only the scheduled weekly email is Scale. On Starter the control carries a lock, the plan name and the monthly cost, at the entry point, never after a report has been built (gated-features pattern rule 7)." },
  { id: "ctl.fee-line", page: "reports", area: "Controls", label: "Exports and prints spend no credits", critical: true, weekly: { ae: 4, marketer: 12, cs: 3, admin: 12 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 25 }, ridgeline: { marketer: 8 } }, note: "A fee statement, so it sits on the control bar beside Export, not inside the Export menu (rule 7). Read attentively the first few times and then read past, which is why the number is lower than the export itself; rule 7 keeps it on screen whatever the number." },
  { id: "ctl.print", page: "reports", area: "Controls", label: "Print or save as PDF", weekly: { ae: 2, marketer: 8, cs: 2, admin: 4 }, overrides: { halyard: { admin: 20 } }, note: "Never gated. Halyard prints for a client who wants paper; the weekly client report itself leaves as a CSV, which Growth includes." },
  { id: "ctl.link", page: "reports", area: "Controls", label: "Copy link with filters", weekly: { ae: 4, marketer: 12, cs: 3, admin: 10 }, overrides: { halyard: { admin: 15 } } },
  { id: "ctl.schedule", page: "reports", area: "Controls", label: "Email this report weekly (Scale)", weekly: { ae: 1, marketer: 4, cs: 1, admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 } }, note: "Scale only; locked at Fathom, Halyard and Ridgeline." },
  { id: "ctl.columns", page: "reports", area: "Controls", label: "Choose columns", weekly: { ae: 2, marketer: 3, cs: 2, admin: 4 } },
  { id: "ctl.chart-table", page: "reports", area: "Controls", label: "Chart or table for the trend", weekly: { ae: 2, marketer: 4, cs: 2, admin: 4 } },
  { id: "ctl.grain", page: "reports", area: "Controls", label: "Time grain (day, week, month)", weekly: { ae: 2, marketer: 4, cs: 2, admin: 4 } },

  // Details on demand
  { id: "det.records", page: "reports", area: "Details on demand", label: "Records behind a number", weekly: { ae: 30, marketer: 18, cs: 18, admin: 30 }, overrides: { halyard: { admin: 40 }, ridgeline: { cs: 30 } }, note: "The main door: a count in a cell opens the drawer listing the records." },
  { id: "det.weeks", page: "reports", area: "Details on demand", label: "Week by week for one row", weekly: { ae: 8, marketer: 10, cs: 5, admin: 8 }, note: "First section of the records drawer." },
  { id: "det.open-record", page: "reports", area: "Details on demand", label: "Open the record from the drawer", weekly: { ae: 18, marketer: 4, cs: 10, admin: 4 }, note: "Navigation to a page, not a third level; Back restores the drawer." },
  { id: "det.steps", page: "reports", area: "Details on demand", label: "Step by step for a sequence", weekly: { ae: 2, marketer: 3, cs: 1, admin: 18 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 55 }, ridgeline: { admin: 2 } }, note: "Expands in place under the sequence row. Apollo's documented gap. Inside the Sequences report, so Starter cannot reach it; Fathom reads step numbers on the Sequences page." },
  { id: "det.audience", page: "reports", area: "Details on demand", label: "Audience breakdown for a campaign", weekly: { ae: 1, marketer: 35, cs: 2, admin: 3 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 40 } } },
  { id: "det.persona", page: "reports", area: "Details on demand", label: "Persona: n, expanding in place beside the audience breakdown", weekly: { ae: 1, marketer: 30, cs: 2, admin: 4 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 35, admin: 5 } }, note: "Reads the personas defined in Settings \u203a Signals, scoring and personas. One definition, two readers." },
  { id: "det.calls", page: "reports", area: "Details on demand", label: "Calls as a record kind in the drawer", weekly: { ae: 6, ae_plus: 40, marketer: 1, cs: 3, admin: 4 }, overrides: { halyard: { admin: 15 }, fathom: { admin: 12 }, ridgeline: { admin: 4 } } },
  { id: "det.definitions", page: "reports", area: "Details on demand", label: "How these numbers are counted", weekly: { ae: 4, marketer: 4, cs: 4, admin: 4 }, note: "Holds the counting toggles too, so definitions and what changes them stay together." },

  // Pipeline report
  { id: "pipe.forecast", page: "reports", area: "Pipeline report", label: "Weighted pipeline", critical: true, weekly: { ae: 45, marketer: 4, cs: 12, admin: 35 }, overrides: { halyard: { admin: 10 }, ridgeline: { ae: 35, cs: 30 } }, note: "Renamed from 'Weighted forecast': on this page Forecast means the number a person submitted, and one word may not mean two things. The method sits under the number (rule 7). On every plan, so it prints on the Pipeline tile row even where the report is locked (gated-features pattern rule 6)." },
  { id: "pipe.breakdown", page: "reports", area: "Pipeline report", label: "By stage or by rep switch", weekly: { ae: 25, marketer: 4, cs: 12, admin: 18 } },
  { id: "pipe.conversion", page: "reports", area: "Pipeline report", label: "Stage-to-stage conversion", weekly: { ae: 10, marketer: 3, cs: 3, admin: 12 }, note: "Expands in place under the by-stage table it depends on." },
  { id: "pipe.lost-reasons", page: "reports", area: "Pipeline report", label: "Lost reasons", weekly: { ae: 8, marketer: 3, cs: 6, admin: 8 }, overrides: { ridgeline: { cs: 15 } }, note: "Expands in place next to the Lost tile." },
  { id: "pipe.coverage", page: "reports", area: "Pipeline report", label: "Win rate and the coverage it requires", weekly: { ae: 12, ae_plus: 55, marketer: 3, cs: 4, admin: 12 }, overrides: { ridgeline: { ae: 10, cs: 5, admin: 10 }, halyard: { admin: 6 }, fathom: { admin: 4 } }, note: "Required coverage is 1 \u00f7 win rate (19\u00a74.5). The last line of the stage-to-stage conversion door, and the same figure the Deals board strip names, so one number is computed once." },
  { id: "pipe.score-first", page: "reports", area: "Pipeline report", label: "Score at first contact, in the Won drawer and its export", weekly: { ae: 3, marketer: 15, cs: 2, admin: 12 }, overrides: { ridgeline: { marketer: 18, admin: 14 }, fathom: { admin: 3 }, halyard: { admin: 3 } }, note: "Stamped with the model version and the date when a person is routed, and never recomputed: a score that moves after the fact cannot be used to validate the model that produced it." },
  { id: "pipe.unweighted", page: "reports", area: "Pipeline report", label: "Unweighted pipeline toggle", weekly: { ae: 3, marketer: 1, cs: 2, admin: 4 } },

  // Activity report
  { id: "act.sort", page: "reports", area: "Activity report", label: "Sort reps", weekly: { ae: 5, marketer: 4, cs: 6, admin: 18 }, overrides: { halyard: { admin: 50 } } },
  { id: "act.trend", page: "reports", area: "Activity report", label: "Weekly activity trend", weekly: { ae: 5, marketer: 10, cs: 6, admin: 15 } },
  { id: "act.meetings", page: "reports", area: "Activity report", label: "Meetings booked", weekly: { ae: 8, marketer: 10, cs: 4, admin: 35 }, overrides: { fathom: { admin: 40 } }, note: "A contact moved to stage Meeting booked; ollopA has no booking tool. Founders count meetings." },

  // Sequences report
  { id: "seq.bounce", page: "reports", area: "Sequences report", label: "Bounce rate", critical: true, weekly: { ae: 1, marketer: 2, cs: 1, admin: 15 }, overrides: { fathom: { admin: 30 }, halyard: { admin: 50 }, ridgeline: { admin: 3 } }, note: "Safety state: warns at 4%, pauses at 6%, the one pair owned by Settings (mail.bounce-guard). On every plan, because safety is never gated (gated-features pattern rule 6)." },
  { id: "seq.sort", page: "reports", area: "Sequences report", label: "Sort sequences by reply rate", weekly: { ae: 2, marketer: 4, cs: 1, admin: 15 }, overrides: { halyard: { admin: 45 } } },
  { id: "seq.bots", page: "reports", area: "Sequences report", label: "Include bot opens", weekly: { ae: 1, marketer: 2, cs: 1, admin: 3 } },
  { id: "seq.archived", page: "reports", area: "Sequences report", label: "Show archived sequences", weekly: { ae: 1, marketer: 1, cs: 1, admin: 3 } },

  // Campaign results
  { id: "camp.conversion", page: "reports", area: "Campaign results", label: "Conversion to pipeline", weekly: { ae: 4, marketer: 40, cs: 3, admin: 10 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 50 } } },
  { id: "reports.camp.sort", page: "reports", area: "Campaign results", label: "Sort campaigns", weekly: { ae: 1, marketer: 25, cs: 2, admin: 3 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 } } },
  { id: "camp.unsub", page: "reports", area: "Campaign results", label: "Unsubscribed: count and rate", critical: true, weekly: { ae: 2, marketer: 45, cs: 2, admin: 18 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 50, admin: 20 } }, note: "Safety state for a sending product, like the bounce rate: it prints on the tile row even where the report is locked." },
  { id: "camp.complaints", page: "reports", area: "Campaign results", label: "Complaints: count and rate", weekly: { ae: 1, marketer: 15, cs: 1, admin: 6 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 18, admin: 8 } } },
  { id: "camp.sourced-influenced", page: "reports", area: "Campaign results", label: "Sourced and influenced pipeline side by side, each printing its convention", weekly: { ae: 4, marketer: 40, cs: 3, admin: 10 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 0 }, ridgeline: { marketer: 45, admin: 12 } }, note: "\"Sourced \u00b7 first touch within 90 days\" under the number. The definition and the window that changes it live together in the definitions door (rule 5)." },
  { id: "camp.internal", page: "reports", area: "Campaign results", label: "Exclude internal contacts", weekly: { ae: 1, marketer: 2, cs: 1, admin: 2 } },

  { id: "act.calls-logged", page: "reports", area: "Activity report", label: "Calls logged per rep", weekly: { ae: 4, ae_plus: 45, marketer: 2, cs: 3, admin: 12 }, overrides: { halyard: { admin: 25 }, fathom: { admin: 18 }, ridgeline: { admin: 6 } } },
  { id: "act.coached", page: "reports", area: "Activity report", label: "Calls with a coaching note in the last 30 days", weekly: { ae: 3, ae_plus: 60, marketer: 1, cs: 2, admin: 4 }, overrides: { halyard: { admin: 8 }, fathom: { admin: 6 }, ridgeline: { admin: 3 } }, note: "A leader-only column: the coaching note lives inside the logged call (spec 07), and this is the count of calls that have one. Listened, with feedback, with a scorecard is the published shape (18§9); ollopA has no recording, so the reading is calls with a note." },
  { id: "act.reps-coached", page: "reports", area: "Activity report", label: "Reps coached this week: 3 of 8", weekly: { ae: 1, ae_plus: 55, marketer: 1, cs: 1, admin: 3 }, overrides: { halyard: { admin: 6 }, fathom: { admin: 4 }, ridgeline: { admin: 2 } }, note: "A tile, and the leader's own adherence number rather than the team's." },

  // Forecast report
  { id: "fc.tab", page: "reports", area: "Forecast report", label: "The Forecast tab", weekly: { ae: 65, ae_plus: 85, cs: 30, admin: 30 }, overrides: { fathom: { admin: 8 }, halyard: { admin: 8 }, ridgeline: { ae: 50, cs: 45, admin: 26 } }, note: "Three journeys land here: the AE before the pipeline call, the AE with reports rolling the team up, and the CSM reading the renewal book. One tab, one panel, one node." },
  { id: "fc.rollup", page: "reports", area: "Forecast report", label: "The five categories as count and sum", weekly: { ae: 70, ae_plus: 80, cs: 35, admin: 30 }, overrides: { fathom: { admin: 8 }, halyard: { admin: 8 }, ridgeline: { ae: 55, cs: 45, admin: 25 } }, note: "The roll-up sits at the seat's position in the hierarchy: own deals for an AE, the team first for an AE with reports, renewal-typed deals for a CSM." },
  { id: "fc.goal", page: "reports", area: "Forecast report", label: "The goal for the period as the denominator, with attainment", weekly: { ae: 55, ae_plus: 70, cs: 25, admin: 15 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 4 }, ridgeline: { ae: 40, cs: 35, admin: 12 } }, note: "A goal is an attribute, not an object (IA-MAP 6.3): set in Settings, Pipeline and data, beside the forecast categories, and shown here as a denominator." },
  { id: "fc.category-defs", page: "reports", area: "Forecast report", label: "Each category's definition, printed under its label", critical: true, weekly: { ae: 12, ae_plus: 14, cs: 10, admin: 4 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 3 }, ridgeline: { ae: 10, cs: 10, admin: 3 } }, note: "Commit reads \"about a 90% number\". A definition in a tooltip is the FTC\u2019s named mechanism; this one is text under the label." },
  { id: "fc.predicted", page: "reports", area: "Forecast report", label: "The predicted number beside the submitted one, with the deals driving the difference", critical: true, weekly: { ae: 45, ae_plus: 60, cs: 20, admin: 15 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 4 }, ridgeline: { ae: 35, cs: 25, admin: 12 } }, note: "Beside, never instead: a prediction that replaces the human number is a forecast nobody owns (rule 6)." },
  { id: "fc.no-agent", page: "reports", area: "Forecast report", label: "No agent submits a forecast", critical: true, weekly: { ae: 8, ae_plus: 10, cs: 5, admin: 4 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 2 }, ridgeline: { ae: 6, cs: 5, admin: 3 } }, note: "Stated beside the predicted-number pair, because that is the one place a reader could think otherwise." },
  { id: "fc.deadline", page: "reports", area: "Forecast report", label: "The submission deadline for this period", critical: true, weekly: { ae: 30, ae_plus: 45, cs: 18, admin: 12 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 3 }, ridgeline: { ae: 25, cs: 20, admin: 10 } }, note: "A commitment with a date on it. Set in Settings, Pipeline and data, with the day, the time and the window." },
  { id: "fc.submitted", page: "reports", area: "Forecast report", label: "The submissions strip: who has submitted for this period and when", weekly: { ae: 18, ae_plus: 65, cs: 10, admin: 35 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 3 }, ridgeline: { ae: 14, cs: 8, admin: 28 } } },
  { id: "fc.scope", page: "reports", area: "Forecast report", label: "The scope chip: your deals, your team, or one rep", weekly: { ae: 14, ae_plus: 45, cs: 12, admin: 4 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 3 }, ridgeline: { ae: 12, cs: 12, admin: 3 } } },
  { id: "fc.split", page: "reports", area: "Forecast report", label: "Renewal base and Expansion upside, with separate totals", weekly: { ae: 4, ae_plus: 5, cs: 35, admin: 4 }, overrides: { ridgeline: { cs: 45, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "The CSM\u2019s reading of the same tab: renewal-typed deals for their book, not a sixth report." },
  { id: "fc.submit", page: "reports", area: "Forecast report", label: "Submit, with its consequence sentence and who receives it", critical: true, weekly: { ae: 65, ae_plus: 75, cs: 30, admin: 8 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 4 }, ridgeline: { ae: 45, cs: 40, admin: 6 } } },
  { id: "fc.adjust", page: "reports", area: "Forecast report", label: "Adjust a category away from the roll-up", weekly: { ae: 45, ae_plus: 55, cs: 20, admin: 3 }, overrides: { ridgeline: { ae: 35, cs: 25, admin: 3 }, fathom: { admin: 3 }, halyard: { admin: 3 } }, note: "The adjustment is the person\u2019s number; it never alters the underlying roll-up, and both are shown." },
  { id: "fc.adjust-note", page: "reports", area: "Forecast report", label: "The judgement note beside the adjustment", weekly: { ae: 40, ae_plus: 50, cs: 18, admin: 3 }, overrides: { ridgeline: { ae: 30, cs: 20, admin: 3 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "fc.last-cycle", page: "reports", area: "Forecast report", label: "Last cycle\u2019s call beside what actually happened", critical: true, weekly: { ae: 35, ae_plus: 55, cs: 15, admin: 6 }, overrides: { ridgeline: { ae: 28, cs: 18, admin: 5 }, fathom: { admin: 3 }, halyard: { admin: 3 } }, note: "Every submission is kept: period, number, split, note, submitted at. The panel opens with the previous call and the outcome side by side, because a forecast with no memory teaches nobody anything." },
  { id: "fc.changes", page: "reports", area: "Forecast report", label: "What changed since the last submission, and who changed it", weekly: { ae: 14, ae_plus: 18, cs: 8, admin: 4 }, overrides: { ridgeline: { ae: 12, cs: 6, admin: 3 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "fc.records-sort", page: "reports", area: "Forecast report", label: "On Forecast the records sort by category then risk, and the drawer says so", weekly: { ae: 12, ae_plus: 16, cs: 8, admin: 3 }, overrides: { ridgeline: { ae: 10, cs: 8, admin: 3 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "fc.starter", page: "reports", area: "Forecast report", label: "On Starter: the number and the goal show; the team roll-up carries the plan name", weekly: { ae: 1, cs: 1, admin: 2 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 1 }, ridgeline: { admin: 1 } } },

  // Freshness
  { id: "data.asof", page: "reports", area: "Freshness", label: "Data as of", critical: true, weekly: { ae: 12, marketer: 20, cs: 8, admin: 25 }, note: "A stale number acted on is a wrong decision (rule 7)." },
]
