import type { UsageItem } from "./model"

// Requests: the admin's intake queue and the request record. Nodes `P-requests` and `R-request`
// (IA-MAP 2.11). Spec: specs/20-requests.md.
//
// Seats: OPS only. No SDR, AE, marketer or CS number exists anywhere in this file, because the
// requester never opens the queue — the answer comes back where the ask was made (the lock panel's
// origin, one line on Home, one line in the next digest) and the area shows the no-access page.
//
// On every plan: this is where an upgrade is asked for, so gating it would gate the sale.
// Both kinds live here, one queue: a change to the workspace (a field, a stage, a workflow, a
// permission, a report) and a locked feature somebody asked for. Two queues for one decision is how
// an approval gets missed (IA-MAP 6.4c; revops walk O5-4).
//
// Baseline describes Meridian, where O9 is monthly and four teams ask at once. Halyard runs ten client
// workspaces, so the same queue is daily and the asks are small — permissions and report columns rather
// than fields 34 people feel. Ridgeline asks less and decides monthly. Fathom is on Starter, everyone
// there is an admin, and the Founder-led profile leaves the page out of the sidebar: the founder meets
// it as her own team's upgrade asks, reached from the Settings plan strip line, and never as an
// intake process (19§4.1 measures that work at 2.1 + 1.8 hours a week when it lives in Slack).

export const requestsItems: UsageItem[] = [
  // The queue
  { id: "rq.queue", page: "requests", area: "The queue", label: "Requests: the requested outcome, the kind, who asked, days waiting, who decides, and the state", weekly: { admin: 50 }, overrides: { fathom: { admin: 10 }, halyard: { admin: 55 }, ridgeline: { admin: 32 } }, note: "The admin's real inbox. 19§4.1: 11 hours a week of manual work per team, of which ad-hoc reporting is 2.1 and permission changes 1.8, and the study says they are unbatchable because \"report requests arrive daily\"." },
  { id: "rq.waiting", page: "requests", area: "The queue", label: "How long each request has waited, oldest first, against the two-business-day answer target", critical: true, weekly: { admin: 42 }, overrides: { fathom: { admin: 9 }, halyard: { admin: 50 }, ridgeline: { admin: 30 } }, note: "A pending decision is decision-critical whatever the number (rule 7). The waiting time is somebody else's week." },
  { id: "rq.states", page: "requests", area: "The queue", label: "State chips with counts: needs a decision, investigating, approved, shipped, verifying", weekly: { admin: 28 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 34 }, ridgeline: { admin: 22 } } },
  { id: "rq.batch", page: "requests", area: "The queue", label: "The whole queue read in one sitting, at a boundary the admin chose, rather than one arrival at a time", weekly: { admin: 22 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 30 }, ridgeline: { admin: 20 } }, note: "PLAN.md: approvals arrive in batches at task boundaries, never as interruptions. Requests are not one of the three interrupting notification kinds; the count reaches the admin in the daily digest." },
  { id: "rq.kind", page: "requests", area: "The queue", label: "Which kind: a change to the workspace, or a locked feature somebody asked for", weekly: { admin: 18 }, overrides: { fathom: { admin: 9 }, halyard: { admin: 24 }, ridgeline: { admin: 14 } } },
  { id: "rq.cost-column", page: "requests", area: "The queue", label: "The monthly total on an upgrade row, in the queue, before the request is opened", critical: true, weekly: { admin: 0 }, overrides: { fathom: { admin: 11 }, halyard: { admin: 16 }, ridgeline: { admin: 9 } }, note: "Approving an upgrade is a price decision, so rule 7 applies to the approver's screen — the total is on the line, not behind it (gated-features pattern rule 5). Zero at Meridian: Scale locks nothing, so the upgrade kind cannot occur there and the column is removed rather than shown empty (rule 4)." },
  { id: "rq.affects-column", page: "requests", area: "The queue", label: "How many people will feel the change, on the row", critical: true, weekly: { admin: 14 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 8 }, ridgeline: { admin: 11 } }, note: "The consequence of the action, which rule 7 keeps out of doors. Lower at Halyard because an agency's asks are one client's permissions, not a required field the whole team meets." },
  { id: "rq.search", page: "requests", area: "The queue", label: "Search and sort; the sort persists per person", weekly: { admin: 8 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 12 }, ridgeline: { admin: 7 } } },
  { id: "rq.views", page: "requests", area: "The queue", label: "Saved views: mine to decide, past the target, waiting on somebody else", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 8 }, ridgeline: { admin: 3 } } },
  { id: "rq.filters", page: "requests", area: "The queue", label: "Additional filters: requester, decision owner, what it touches, kind, archived (5)", weekly: { admin: 4 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 6 }, ridgeline: { admin: 3 } } },
  { id: "rq.columns", page: "requests", area: "The queue", label: "Columns: 9 of 14", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } } },
  { id: "rq.export", page: "requests", area: "The queue", label: "Export the queue", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } }, note: "Exporting a table a seat can already read is on every plan (spec 14 owns that sentence)." },

  // The ask
  { id: "rq.outcome", page: "requests", area: "The ask", label: "What the person should be able to do after the change, in their own words", weekly: { admin: 38 }, overrides: { fathom: { admin: 9 }, halyard: { admin: 46 }, ridgeline: { admin: 28 } }, note: "19§8.2, verbatim: \"Requested outcome. Explain what someone should be able to do after the change.\" It is the first field because capture comes before estimating." },
  { id: "rq.requester", page: "requests", area: "The ask", label: "Who asked, which seat they hold, and when", weekly: { admin: 32 }, overrides: { fathom: { admin: 9 }, halyard: { admin: 40 }, ridgeline: { admin: 24 } } },
  { id: "rq.reason", page: "requests", area: "The ask", label: "The reason: new information, an approved decision, or a defect in the current result", weekly: { admin: 18 }, overrides: { fathom: { admin: 7 }, halyard: { admin: 20 }, ridgeline: { admin: 14 } }, note: "19§8.2's three reasons, offered as three named choices with one line of text, so \"real gap or preference\" (O9's own decision) is answerable." },
  { id: "rq.origin", page: "requests", area: "The ask", label: "Where it came from: a locked control, the no-access page, a report, a permission, a field or stage, a routing rule", weekly: { admin: 16 }, overrides: { fathom: { admin: 10 }, halyard: { admin: 18 }, ridgeline: { admin: 12 } }, note: "Six sources, one queue. The origin is captured by the product rather than typed, and it prefills the reason field the ask panel collects." },
  { id: "rq.evidence", page: "requests", area: "The ask", label: "What the requester attached: the record, the view or the report they were looking at", weekly: { admin: 4 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 3 } } },
  { id: "rq.estimate", page: "requests", area: "The ask", label: "The impact estimate, written after the request is captured and never before", weekly: { admin: 8 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 5 } }, note: "19§8.2: \"Capture the request before estimating it.\" The field is present but empty until the state passes captured." },
  { id: "rq.duplicate", page: "requests", area: "The ask", label: "Two people asked for the same thing: merged, with both names kept", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 6 }, ridgeline: { admin: 2 } } },
  { id: "rq.form", page: "requests", area: "The ask", label: "The shape of the ask: which questions a requester answers when they raise one", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } } },

  // The decision
  { id: "rq.state", page: "requests", area: "The decision", label: "The state: captured, investigating, approved, shipped, verified", critical: true, weekly: { admin: 30 }, overrides: { fathom: { admin: 7 }, halyard: { admin: 38 }, ridgeline: { admin: 22 } }, note: "Five states, and the word is the state: no percentage, no progress ring." },
  { id: "rq.owner", page: "requests", area: "The decision", label: "The decision owner, named by the decision they own", weekly: { admin: 24 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 24 }, ridgeline: { admin: 18 } }, note: "19§8.2: \"Identify stakeholders by the decision they own.\" Low at Fathom because everyone there is an admin and the owner is always the founder — which is the honest reading, not a gap." },
  { id: "rq.answer-target", page: "requests", area: "The decision", label: "The answer this queue owes: two business days to a first decision, and which requests are past it", critical: true, weekly: { admin: 22 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 28 }, ridgeline: { admin: 20 } }, note: "The intake SLA the research names: a deal desk's published target is \"same or next business day\" for standard asks and 2–3 business days for complex multi-approver ones, with DealHub tiering 24h / 48h / 72h (18§ deal desk). Two business days to an answer, not to a shipped change." },
  { id: "rq.approve-investigate", page: "requests", area: "The decision", label: "Approve to investigate: what it does not change, and that nobody feels it yet", weekly: { admin: 14 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 20 }, ridgeline: { admin: 10 } }, note: "19§8.2: \"Separate approval to investigate from approval to implement.\" This one carries no consequence line, and saying so is the point of separating them." },
  { id: "rq.approve-implement", page: "requests", area: "The decision", label: "Approve to implement: the consequence in the label and again in the confirmation", critical: true, weekly: { admin: 14 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 20 }, ridgeline: { admin: 10 } }, note: "\"Approve · adds a required field at Proposal · 34 people see a new required field · rollback: remove the field, values kept 30 days.\" PLAN.md's approval rule, written for agents, applies to an admin changing what other people see." },
  { id: "rq.two-dates", page: "requests", area: "The decision", label: "The two approvals as two separately-dated actions, each with who gave it", critical: true, weekly: { admin: 10 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 12 }, ridgeline: { admin: 7 } }, note: "19§8.2 asks for a decision owner and a decision date; two approvals mean two dates, and one field cannot hold both." },
  { id: "rq.decline", page: "requests", area: "The decision", label: "Decline with a reason, which the requester reads where they asked", critical: true, weekly: { admin: 12 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 16 }, ridgeline: { admin: 8 } }, note: "The path to decline is no longer than the path to approve (rule 7), and the reason is required: a decline with no reason is a request that will be asked again next month." },
  { id: "rq.bulk", page: "requests", area: "The decision", label: "Several approved to investigate at once; never several approved to implement", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 8 }, ridgeline: { admin: 3 } }, note: "Rule 7's corollary: disclosure that exceeds review capacity is equivalent to hiding (88.5% seen, 23.9% stopped). Investigating changes nothing, so it batches; implementing is read one at a time." },
  { id: "rq.hand-over", page: "requests", area: "The decision", label: "Hand the decision to the person who owns it, with one line saying why", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 3 } } },
  { id: "rq.default-owner", page: "requests", area: "The decision", label: "Who a kind of request goes to when nobody is named", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } } },
  { id: "rq.no-autoclose", page: "requests", area: "The decision", label: "What happens to a request nobody answers: nothing closes itself, and the queue says so", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } } },

  // What it changes
  { id: "rq.touches", page: "requests", area: "What it changes", label: "What it touches: the field, stage, workflow, permission profile or plan feature, each a link to the thing itself", weekly: { admin: 16 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 10 }, ridgeline: { admin: 12 } }, note: "19§8.2's \"affected HubSpot setup\", read as a link rather than a sentence: the change and the place it happens are one click apart." },
  { id: "rq.affected-people", page: "requests", area: "What it changes", label: "Who will see the change, named and counted, and how the count was made", critical: true, weekly: { admin: 12 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 6 }, ridgeline: { admin: 8 } } },
  { id: "rq.scope", page: "requests", area: "What it changes", label: "Applies to: one team, one territory, or everyone — and widened later from the same row", critical: true, weekly: { admin: 10 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 7 } }, note: "Ollopa's answer to \"build and test somewhere safe\" (IA-MAP 6.2): staged rollout, because a sandbox is a second copy of the workspace. 19§8.3: \"deploy in smaller, safer batches rather than all at once.\"" },
  { id: "rq.rollback", page: "requests", area: "What it changes", label: "The rollback path in words, and what happens to values already entered", critical: true, weekly: { admin: 10 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 5 }, ridgeline: { admin: 7 } }, note: "19 JD-3 names it as a duty: \"sandbox-first changes, tested deployments, documented rollback paths.\" An undo nobody has written down is not an undo." },
  { id: "rq.baseline", page: "requests", area: "What it changes", label: "The approved baseline: what the setup did before this request", weekly: { admin: 4 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 3 }, ridgeline: { admin: 4 } } },
  { id: "rq.staged", page: "requests", area: "What it changes", label: "What Ollopa does instead of a sandbox, stated on the row: no sandbox, no change set, no diff", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 3 } } },

  // Rollout and verification
  { id: "rq.announce", page: "requests", area: "Rollout and verification", label: "Shipping writes one line into the affected people's Home strip and their next digest", weekly: { admin: 9 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 5 } }, note: "One announcement mechanism for the whole product (spec 00 §3.4, spec 01's health strip, spec 19's routing changes). 19§8.4: \"The sandbox rehearses the system; nothing rehearses the reps.\" Not a tour, not a tooltip, not a modal." },
  { id: "rq.verify", page: "requests", area: "Rollout and verification", label: "Verified: how many of the affected people have used the changed thing since it shipped, over the affected count", weekly: { admin: 10 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 7 } }, note: "19§8.4: \"Attendance tells you who joined the training. It does not tell you who can complete the work.\" A behaviour count, not a completion tick, and it is the implementation evidence 19§8.2 asks for." },
  { id: "rq.verify-open", page: "requests", area: "Rollout and verification", label: "Shipped but not verified, with how long since", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 4 } } },
  { id: "rq.reopen", page: "requests", area: "Rollout and verification", label: "Reopen a verified request when the change did not hold", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 2 } } },
  { id: "rq.notify-requester", page: "requests", area: "Rollout and verification", label: "What the requester is told, and where: the answer returns to the place the ask was made", weekly: { admin: 4 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 6 }, ridgeline: { admin: 3 } }, note: "The requester's seat does not hold this page, so the decision travels to them rather than the other way round: the lock they met, one line on Home, one line in the digest." },

  // The upgrade kind
  { id: "rq.upg-feature", page: "requests", area: "The upgrade kind", label: "The feature asked for, the plan that carries it, and what the person was trying to do when they met the lock", critical: true, weekly: { admin: 0 }, overrides: { fathom: { admin: 14 }, halyard: { admin: 16 }, ridgeline: { admin: 9 } }, note: "Figma's shipped flow carries requester, seat type, cost, origin, reason and time; Ollopa carries those plus the feature (RULES.md, gated features rule 5)." },
  { id: "rq.upg-total", page: "requests", area: "The upgrade kind", label: "The new total for the period, stated before the button", critical: true, weekly: { admin: 0 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 14 }, ridgeline: { admin: 8 } }, note: "One total, never a breakdown: partitioned pricing left consumers underestimating the total by about 11%, worse than drip pricing's 3.2%." },
  { id: "rq.upg-count", page: "requests", area: "The upgrade kind", label: "How many people have asked for the same locked feature, and when", weekly: { admin: 0 }, overrides: { fathom: { admin: 10 }, halyard: { admin: 6 }, ridgeline: { admin: 4 } }, note: "The second such ask in a week is also the signal that puts this page in a Founder-led sidebar for two weeks (IA-MAP 6.4a)." },
  { id: "rq.upg-alt", page: "requests", area: "The upgrade kind", label: "What is still possible without the upgrade — the same line the lock panel showed", weekly: { admin: 0 }, overrides: { fathom: { admin: 8 }, halyard: { admin: 4 }, ridgeline: { admin: 3 } }, note: "The approver reads what the asker read; a door that opens onto a dead end is a door that lied (spec 14 §3.4)." },
  { id: "rq.upg-declined", page: "requests", area: "The upgrade kind", label: "A declined upgrade: the lock stays where it was, the reason reaches the person at it, and nothing moves", weekly: { admin: 0 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } }, note: "The whole upgrade group is removed at Meridian, where nothing is locked: five rows that exist at the other three businesses and cannot occur on Scale." },

  // Evidence and discussion
  { id: "rq.discussion", page: "requests", area: "Evidence and discussion", label: "The discussion · n notes", weekly: { admin: 9 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 10 }, ridgeline: { admin: 6 } } },
  { id: "rq.impl", page: "requests", area: "Evidence and discussion", label: "Implementation evidence and the test result", weekly: { admin: 8 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 4 } } },
  { id: "rq.impl-test", page: "requests", area: "Evidence and discussion", label: "What was tested, on what, by whom, and the result", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 3 } } },
  { id: "rq.history", page: "requests", area: "Evidence and discussion", label: "Full history: what changed on this request, who changed it and when", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } } },
  { id: "rq.link-related", page: "requests", area: "Evidence and discussion", label: "Link a request to the one it came out of", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } } },
  { id: "rq.copy-out", page: "requests", area: "Evidence and discussion", label: "A request that belongs in the company's own tracker: copy its link and its fields out", weekly: { admin: 3 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } } },
  { id: "rq.retention", page: "requests", area: "Evidence and discussion", label: "How long declined and archived requests are kept", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 2 } } },
  { id: "rq.archive", page: "requests", area: "Evidence and discussion", label: "Archive a declined or superseded request: what is kept and what stops", weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 }, ridgeline: { admin: 2 } } },
]
