import type { UsageItem } from "./model"

// Sequences: the list with stats and the sequence page (steps, people, settings, results). Spec: specs/05-sequences.md.
// Baseline numbers describe Meridian Software (about 15 SDRs, 26 sequences). A sequence is built once and runs for months,
// so reading and running are weekly; building is monthly.
// Fathom: the founder and the one SDR do all the outbound; everyone is an admin, so "admin" here is a founder sending email.
// Halyard: about four sequences per client workspace, set up ten times over; duplicate and the sending mailbox are routine.
// Ridgeline: almost no outbound; two sequences (renewal and expansion) touched by the inbound SDR, the expansion AE and CS.
// Marketer and CS have no Sequences entry in the navigation; they arrive by link from a contact or an account, so their numbers are small.

export const sequencesItems: UsageItem[] = [
  // List
  { id: "seq.list.table", page: "sequences", area: "List", label: "Sequence list with status and counts", weekly: { sdr: 90, ae: 30, marketer: 8, cs: 4, admin: 25 }, overrides: { fathom: { sdr: 95, admin: 85 }, halyard: { sdr: 95, admin: 70 }, ridgeline: { sdr: 30, ae: 15, marketer: 5, cs: 12, admin: 8 } } },
  { id: "seq.list.open", page: "sequences", area: "List", label: "Open a sequence", weekly: { sdr: 90, ae: 25, marketer: 6, cs: 4, admin: 22 }, overrides: { fathom: { sdr: 95, admin: 85 }, halyard: { sdr: 95, admin: 70 }, ridgeline: { sdr: 28, ae: 14, marketer: 4, cs: 12, admin: 8 } } },
  { id: "seq.list.health", page: "sequences", area: "List", label: "Bounce guard state per sequence", critical: true, weekly: { sdr: 15, ae: 3, admin: 30 }, overrides: { halyard: { sdr: 30, admin: 50 }, fathom: { sdr: 15, admin: 25 }, ridgeline: { sdr: 3, admin: 5 } }, note: "Auto-paused by bounce guard is safety state (rule 7): visible on every row whatever the usage." },
  { id: "seq.list.pause-resume", page: "sequences", area: "List", label: "Pause or resume from the list", weekly: { sdr: 25, ae: 5, admin: 10 }, overrides: { fathom: { sdr: 15, admin: 18 }, halyard: { sdr: 18, admin: 18 }, ridgeline: { sdr: 5, ae: 3, cs: 3, admin: 3 } } },
  { id: "seq.list.search", page: "sequences", area: "List", label: "Search sequences", weekly: { sdr: 10, ae: 6, admin: 6 }, overrides: { fathom: { sdr: 2, admin: 2 }, halyard: { sdr: 4, admin: 4 }, ridgeline: { sdr: 2, ae: 2, admin: 2 } }, note: "26 sequences fit on one screen at Meridian; Fathom has four and a Halyard workspace about four." },
  { id: "seq.list.filter-status", page: "sequences", area: "List", label: "Filter by status", weekly: { sdr: 10, ae: 4, admin: 6 }, overrides: { fathom: { sdr: 2, admin: 2 }, halyard: { sdr: 4, admin: 4 }, ridgeline: { sdr: 2, admin: 2 } } },
  { id: "seq.list.filter-owner", page: "sequences", area: "List", label: "Filter by owner (Mine)", weekly: { sdr: 15, ae: 6, admin: 10 }, overrides: { fathom: { sdr: 0, admin: 0 }, halyard: { sdr: 4, admin: 6 }, ridgeline: { sdr: 3, admin: 3 } }, note: "Fathom has one SDR and one founder sending; there is nothing to filter, so the chip is removed." },
  { id: "seq.list.sort", page: "sequences", area: "List", label: "Sort by a column", weekly: { sdr: 4, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 1, admin: 1 }, halyard: { sdr: 3, admin: 4 } } },
  { id: "seq.list.columns", page: "sequences", area: "List", label: "Choose columns", weekly: { sdr: 3, admin: 3 } },
  { id: "seq.list.new", page: "sequences", area: "List", label: "New sequence", weekly: { sdr: 8, ae: 3, admin: 3 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 2, ae: 2, cs: 2, admin: 1 } } },
  { id: "seq.list.duplicate", page: "sequences", area: "List", label: "Duplicate a sequence", weekly: { sdr: 4, ae: 1, admin: 3 }, overrides: { fathom: { sdr: 4, admin: 5 }, halyard: { sdr: 20, admin: 25 }, ridgeline: { sdr: 1, admin: 1 } }, note: "At Halyard the same sequence is copied into each client workspace; promoted to a visible button there." },
  { id: "seq.list.archive", page: "sequences", area: "List", label: "Archive a sequence", weekly: { sdr: 3, ae: 1, admin: 4 }, overrides: { fathom: { sdr: 2, admin: 3 }, halyard: { sdr: 4, admin: 6 }, ridgeline: { admin: 1 } }, note: "Halyard archives a client's sequences when the client leaves." },
  { id: "seq.list.bulk", page: "sequences", area: "List", label: "Select several: pause, resume, archive", weekly: { sdr: 3, admin: 3 }, overrides: { halyard: { sdr: 3, admin: 8 }, fathom: { sdr: 1, admin: 2 } } },
  { id: "seq.list.archived", page: "sequences", area: "List", label: "Show archived sequences", weekly: { sdr: 2, admin: 3 }, overrides: { halyard: { admin: 4 } } },

  // Sequence header
  { id: "seq.page.counts", page: "sequences", area: "Sequence header", label: "People by status (active, paused, finished, replied, bounced, not sent)", weekly: { sdr: 85, ae: 25, marketer: 6, cs: 4, admin: 22 }, overrides: { fathom: { sdr: 90, admin: 80 }, halyard: { sdr: 90, admin: 65 }, ridgeline: { sdr: 28, ae: 14, marketer: 4, cs: 12, admin: 8 } } },
  { id: "seq.page.results", page: "sequences", area: "Sequence header", label: "Results strip (sent, delivered, opened, replied, interested, meetings)", weekly: { sdr: 25, ae: 10, marketer: 8, cs: 3, admin: 20 }, overrides: { fathom: { sdr: 30, admin: 35 }, halyard: { sdr: 40, admin: 45 }, ridgeline: { sdr: 8, ae: 6, marketer: 5, cs: 6, admin: 6 } }, note: "Counts and rates side by side; never a rate with the count on hover." },
  { id: "seq.page.health", page: "sequences", area: "Sequence header", label: "Bounce rate and bounce guard state", critical: true, weekly: { sdr: 20, ae: 4, admin: 35 }, overrides: { halyard: { sdr: 30, admin: 50 }, fathom: { sdr: 20, admin: 30 }, ridgeline: { sdr: 3, admin: 5 } }, note: "Safety state and the threshold that stops sending (rule 7)." },
  { id: "seq.page.status", page: "sequences", area: "Sequence header", label: "Pause or resume the sequence", weekly: { sdr: 30, ae: 6, admin: 10 }, overrides: { fathom: { sdr: 20, admin: 20 }, halyard: { sdr: 30, admin: 25 }, ridgeline: { sdr: 6, ae: 3, cs: 4, admin: 3 } }, note: "The consequence (people keep their place; nothing is deleted) is written next to the button." },
  { id: "seq.page.rename", page: "sequences", area: "Sequence header", label: "Rename", weekly: { sdr: 4, admin: 2 }, overrides: { halyard: { sdr: 6, admin: 8 } } },
  { id: "seq.page.owner", page: "sequences", area: "Sequence header", label: "Change owner", weekly: { sdr: 1, admin: 4 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 6 } }, note: "Meridian reassigns when someone leaves; Halyard when a client moves between specialists. Removed at Fathom: nobody to hand to." },
  { id: "seq.page.share", page: "sequences", area: "Sequence header", label: "Who can see and edit", weekly: { sdr: 4, ae: 2, admin: 4 }, overrides: { fathom: { sdr: 0, admin: 0 }, halyard: { admin: 4 } }, note: "At Fathom everyone is an admin; the item is removed, not disabled." },
  { id: "seq.page.duplicate", page: "sequences", area: "Sequence header", label: "Duplicate (from the page)", weekly: { sdr: 3, ae: 1, admin: 3 }, overrides: { halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 1, admin: 1 } } },
  { id: "seq.page.archive", page: "sequences", area: "Sequence header", label: "Archive (from the page)", weekly: { sdr: 3, admin: 4 }, overrides: { halyard: { sdr: 4, admin: 6 }, ridgeline: { admin: 1 } }, note: "The archive dialog states how many people stop and how many scheduled emails are deleted (rule 7)." },
  { id: "seq.page.delete-draft", page: "sequences", area: "Sequence header", label: "Delete draft", weekly: { sdr: 2, admin: 1 }, overrides: { halyard: { sdr: 2, admin: 3 } }, note: "Only exists while the sequence is a draft with nobody in it; otherwise removed." },

  // Steps
  { id: "seq.steps.list", page: "sequences", area: "Steps", label: "Steps with per-step results", weekly: { sdr: 80, ae: 20, marketer: 6, cs: 3, admin: 20 }, overrides: { fathom: { sdr: 85, admin: 80 }, halyard: { sdr: 85, admin: 60 }, ridgeline: { sdr: 22, ae: 10, marketer: 4, cs: 10, admin: 6 } } },
  { id: "seq.steps.expand", page: "sequences", area: "Steps", label: "Open a step to read or edit it", weekly: { sdr: 40, ae: 8, admin: 8 }, overrides: { fathom: { sdr: 45, admin: 40 }, halyard: { sdr: 50, admin: 30 }, ridgeline: { sdr: 10, ae: 4, cs: 6, admin: 3 } } },
  { id: "seq.steps.edit-email", page: "sequences", area: "Steps", label: "Edit email subject and body", weekly: { sdr: 12, ae: 3, admin: 3 }, overrides: { fathom: { sdr: 20, admin: 22 }, halyard: { sdr: 20, admin: 12 }, ridgeline: { sdr: 5, ae: 2, cs: 4, admin: 1 } }, note: "Built once, run for months at Meridian; rewritten per client at Halyard; rewritten by the founder at Fathom." },
  { id: "seq.steps.variables", page: "sequences", area: "Steps", label: "Insert a variable (first name, company, signal)", weekly: { sdr: 6, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 12 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 2, cs: 2 } } },
  { id: "seq.steps.preview", page: "sequences", area: "Steps", label: "Preview a step for one person", weekly: { sdr: 8, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 12 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 3, cs: 3 } } },
  { id: "seq.steps.agent-draft", page: "sequences", area: "Steps", label: "Ask the outreach agent to draft the step", weekly: { sdr: 10, admin: 2 }, overrides: { fathom: { sdr: 30, admin: 30 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 3, cs: 2 } }, note: "Fathom has nobody with time to write; the agent drafts and a human approves." },
  { id: "seq.steps.variants", page: "sequences", area: "Steps", label: "A/B variants on an email step", weekly: { sdr: 4, admin: 2 }, overrides: { fathom: { sdr: 3, admin: 4 }, halyard: { sdr: 5, admin: 4 }, ridgeline: { sdr: 1 } } },
  { id: "seq.steps.add", page: "sequences", area: "Steps", label: "Add a step", weekly: { sdr: 8, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 12 }, ridgeline: { sdr: 2, cs: 2, admin: 1 } } },
  { id: "seq.steps.wait", page: "sequences", area: "Steps", label: "Change a wait", weekly: { sdr: 5, admin: 2 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 8, admin: 5 }, ridgeline: { sdr: 2, cs: 2 } } },
  { id: "seq.steps.reorder", page: "sequences", area: "Steps", label: "Reorder steps", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 }, fathom: { sdr: 4, admin: 4 } } },
  { id: "seq.steps.delete", page: "sequences", area: "Steps", label: "Delete a step", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 }, fathom: { sdr: 4, admin: 4 } }, note: "The dialog says how many people are waiting at the step and where they go next." },
  { id: "seq.steps.change-type", page: "sequences", area: "Steps", label: "Change a step's type", weekly: { sdr: 2, admin: 1 }, overrides: { halyard: { sdr: 2 } } },
  { id: "seq.steps.people-at-step", page: "sequences", area: "Steps", label: "Who is at this step now", weekly: { sdr: 6, ae: 2, admin: 2 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 8, admin: 4 }, ridgeline: { sdr: 2, cs: 2 } } },
  { id: "seq.steps.skip-toggle", page: "sequences", area: "Steps", label: "Turn a step off without deleting it", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 } }, note: "A step that is off is shown greyed with the word Off; the sequence never skips a step silently." },
  { id: "seq.steps.activate", page: "sequences", area: "Steps", label: "Activate a draft", weekly: { sdr: 6, ae: 2, admin: 2 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 2, cs: 2, admin: 1 } } },
  { id: "seq.steps.expand-all", page: "sequences", area: "Steps", label: "Expand or collapse all steps", weekly: { sdr: 4, admin: 2 }, overrides: { halyard: { sdr: 6, admin: 4 }, fathom: { sdr: 6, admin: 6 } } },

  // People in the sequence
  { id: "seq.people.table", page: "sequences", area: "People", label: "People in the sequence with status and step", weekly: { sdr: 75, ae: 25, marketer: 4, cs: 4, admin: 15 }, overrides: { fathom: { sdr: 80, admin: 75 }, halyard: { sdr: 85, admin: 55 }, ridgeline: { sdr: 25, ae: 14, cs: 12, admin: 5 } } },
  { id: "seq.people.filter-status", page: "sequences", area: "People", label: "Filter people by status", weekly: { sdr: 35, ae: 8, admin: 8 }, overrides: { fathom: { sdr: 30, admin: 25 }, halyard: { sdr: 40, admin: 25 }, ridgeline: { sdr: 10, ae: 4, cs: 5, admin: 2 } } },
  { id: "seq.people.search", page: "sequences", area: "People", label: "Find a person in the sequence", weekly: { sdr: 10, ae: 6, admin: 3 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 10, admin: 4 }, ridgeline: { sdr: 4, ae: 3, cs: 3 } } },
  { id: "seq.people.add", page: "sequences", area: "People", label: "Add people", weekly: { sdr: 50, ae: 15, cs: 3, admin: 6 }, overrides: { fathom: { sdr: 60, admin: 55 }, halyard: { sdr: 65, admin: 35 }, ridgeline: { sdr: 20, ae: 12, cs: 10, admin: 3 } }, note: "Most enrolment happens from People and Lists; this is the second door in." },
  { id: "seq.people.open-reply", page: "sequences", area: "People", label: "Open the reply in Inbox", weekly: { sdr: 30, ae: 12, admin: 3 }, overrides: { fathom: { sdr: 35, admin: 30 }, halyard: { sdr: 40, admin: 12 }, ridgeline: { sdr: 12, ae: 8, cs: 4 } } },
  { id: "seq.people.pause-person", page: "sequences", area: "People", label: "Pause one person", weekly: { sdr: 12, ae: 6, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 10 }, halyard: { sdr: 15, admin: 6 }, ridgeline: { sdr: 5, ae: 4, cs: 4 } } },
  { id: "seq.people.remove-person", page: "sequences", area: "People", label: "Remove one person", weekly: { sdr: 6, ae: 3, admin: 2 }, overrides: { halyard: { sdr: 8, admin: 4 }, ridgeline: { sdr: 3, ae: 2, cs: 3 } } },
  { id: "seq.people.finish-person", page: "sequences", area: "People", label: "Mark one person finished", weekly: { sdr: 5, ae: 3, admin: 1 }, overrides: { halyard: { sdr: 6, admin: 3 }, ridgeline: { sdr: 2, cs: 2 } } },
  { id: "seq.people.retry", page: "sequences", area: "People", label: "Fix the email and retry a not-sent person", weekly: { sdr: 8, admin: 5 }, overrides: { fathom: { sdr: 8, admin: 10 }, halyard: { sdr: 10, admin: 8 }, ridgeline: { sdr: 3 } } },
  { id: "seq.people.move-step", page: "sequences", area: "People", label: "Move a person to another step", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 3 } } },
  { id: "seq.people.bulk", page: "sequences", area: "People", label: "Select several people: pause, resume, finish, remove", weekly: { sdr: 4, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 5, admin: 6 }, halyard: { sdr: 6, admin: 6 }, ridgeline: { sdr: 2, cs: 2 } } },
  { id: "seq.people.export", page: "sequences", area: "People", label: "Export people (CSV)", weekly: { sdr: 2, marketer: 3, admin: 3 }, overrides: { halyard: { admin: 4 } } },

  // Settings of this sequence
  { id: "seq.settings.mailbox", page: "sequences", area: "Settings", label: "Sending mailbox and today's limit", weekly: { sdr: 5, ae: 2, admin: 6 }, overrides: { fathom: { sdr: 8, admin: 10 }, halyard: { sdr: 20, admin: 22 }, ridgeline: { sdr: 2, cs: 2, admin: 2 } }, note: "Each Halyard client sends from its own mailboxes. The current value is always shown in the header; changing it is the door." },
  { id: "seq.settings.schedule", page: "sequences", area: "Settings", label: "Sending schedule", weekly: { sdr: 4, ae: 1, admin: 5 }, overrides: { fathom: { sdr: 4, admin: 5 }, halyard: { sdr: 10, admin: 10 }, ridgeline: { sdr: 2, cs: 2, admin: 2 } }, note: "Client time zones at Halyard. Schedules are defined in Settings; picked here." },
  { id: "seq.settings.ruleset", page: "sequences", area: "Settings", label: "Ruleset", weekly: { sdr: 3, admin: 5 }, overrides: { fathom: { sdr: 3, admin: 4 }, halyard: { sdr: 5, admin: 6 }, ridgeline: { cs: 2, admin: 1 } } },
  { id: "seq.settings.priority", page: "sequences", area: "Settings", label: "Priority among sequences", weekly: { sdr: 3, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 } } },
  { id: "seq.settings.daily-cap", page: "sequences", area: "Settings", label: "Emails per day from this sequence", weekly: { sdr: 3, admin: 4 }, overrides: { halyard: { sdr: 8, admin: 10 }, fathom: { sdr: 4, admin: 5 } }, note: "Shares the mailbox limit set in Settings; the two numbers are shown together (rule 5)." },
  { id: "seq.settings.tracking", page: "sequences", area: "Settings", label: "Open and click tracking for this sequence", weekly: { sdr: 2, marketer: 3, admin: 2 } },

  // Results and history
  { id: "seq.results.by-step", page: "sequences", area: "Results", label: "Results by step and by audience", weekly: { sdr: 10, ae: 3, marketer: 8, cs: 2, admin: 10 }, overrides: { fathom: { sdr: 10, admin: 15 }, halyard: { sdr: 15, admin: 25 }, ridgeline: { sdr: 4, marketer: 6, cs: 4, admin: 3 } }, note: "Halyard reports results to clients weekly, so it is promoted for the ops lead." },
  { id: "seq.history", page: "sequences", area: "History", label: "Change history (edits, pauses, bounce guard events)", weekly: { sdr: 3, admin: 10 }, overrides: { halyard: { sdr: 4, admin: 15 }, fathom: { admin: 3 } } },
]
