import type { UsageItem } from "./model"

// Sequences: the list with stats and the sequence page (steps, people, settings, results). Spec: specs/05-sequences.md.
// Baseline numbers describe Meridian Software (about 15 SDRs, 26 sequences). A sequence is built once and runs for months,
// so reading and running are weekly; building is monthly.
// Fathom: the founder and the one SDR do all the outbound; everyone is an admin, so "admin" here is a founder sending email.
// Halyard: about four sequences per client workspace, set up ten times over; duplicate and the sending mailbox are routine.
// Ridgeline: almost no outbound; two sequences (renewal and expansion) touched by the inbound SDR, the expansion AE and CS.
// Marketer and CS have no Sequences area: the navigation decides area access by seat, so a link lands them on the
// no-access page naming who uses Sequences and who to ask (PLAN, 14 Sep 2026, the three kinds of "cannot see it").
// They therefore carry no numbers here. Reading one sequence they were given is an object permission, not an area view.
// Destructive actions carry critical: true, so archive, delete draft and delete step are never hidden and always state
// what they destroy.

export const sequencesItems: UsageItem[] = [
  // List
  { id: "seq.list.table", page: "sequences", area: "List", label: "Sequence list with status and counts", weekly: { sdr: 90, ae: 30, admin: 25 }, overrides: { fathom: { sdr: 95, admin: 85 }, halyard: { sdr: 95, admin: 70 }, ridgeline: { sdr: 30, ae: 15, admin: 8 } } },
  { id: "seq.list.open", page: "sequences", area: "List", label: "Open a sequence", weekly: { sdr: 90, ae: 25, admin: 22 }, overrides: { fathom: { sdr: 95, admin: 85 }, halyard: { sdr: 95, admin: 70 }, ridgeline: { sdr: 28, ae: 14, admin: 8 } } },
  { id: "seq.list.health", page: "sequences", area: "List", label: "Bounce guard state per sequence", critical: true, weekly: { sdr: 15, ae: 3, admin: 30 }, overrides: { halyard: { sdr: 30, admin: 50 }, fathom: { sdr: 15, admin: 25 }, ridgeline: { sdr: 3, admin: 5 } }, note: "Auto-paused by bounce guard is safety state (rule 7): visible on every row whatever the usage." },
  { id: "seq.list.pause-resume", page: "sequences", area: "List", label: "Pause or resume from the list", weekly: { sdr: 25, ae: 5, admin: 10 }, overrides: { fathom: { sdr: 15, admin: 18 }, halyard: { sdr: 18, admin: 18 }, ridgeline: { sdr: 5, ae: 3, admin: 3 } } },
  { id: "seq.list.search", page: "sequences", area: "List", label: "Search sequences", weekly: { sdr: 10, ae: 6, admin: 6 }, overrides: { fathom: { sdr: 2, admin: 2 }, halyard: { sdr: 4, admin: 4 }, ridgeline: { sdr: 2, ae: 2, admin: 2 } }, note: "26 sequences fit on one screen at Meridian; Fathom has four and a Halyard workspace about four." },
  { id: "seq.list.filter-status", page: "sequences", area: "List", label: "Filter by status", weekly: { sdr: 10, ae: 4, admin: 6 }, overrides: { fathom: { sdr: 2, admin: 2 }, halyard: { sdr: 4, admin: 4 }, ridgeline: { sdr: 2, admin: 2 } } },
  { id: "seq.list.filter-owner", page: "sequences", area: "List", label: "Filter by owner (Mine)", weekly: { sdr: 15, ae: 6, admin: 10 }, overrides: { fathom: { sdr: 0, admin: 0 }, halyard: { sdr: 4, admin: 6 }, ridgeline: { sdr: 3, admin: 3 } }, note: "Fathom has one SDR and one founder sending; there is nothing to filter, so the chip is removed." },
  { id: "seq.list.sort", page: "sequences", area: "List", label: "Sort by a column", weekly: { sdr: 4, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 1, admin: 1 }, halyard: { sdr: 3, admin: 4 } } },
  { id: "seq.list.columns", page: "sequences", area: "List", label: "Choose columns", weekly: { sdr: 3, admin: 3 } },
  { id: "seq.list.new", page: "sequences", area: "List", label: "New sequence", weekly: { sdr: 8, ae: 3, admin: 3 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 2, ae: 2, admin: 1 } } },
  { id: "seq.list.duplicate", page: "sequences", area: "List", label: "Duplicate a sequence", weekly: { sdr: 4, ae: 1, admin: 3 }, overrides: { fathom: { sdr: 4, admin: 5 }, halyard: { sdr: 20, admin: 25 }, ridgeline: { sdr: 1, admin: 1 } }, note: "At Halyard the same sequence is copied into each client workspace; promoted to a visible button there." },
  { id: "seq.list.archive", page: "sequences", area: "List", label: "Archive a sequence", critical: true, weekly: { sdr: 3, ae: 1, admin: 4 }, overrides: { fathom: { sdr: 2, admin: 3 }, halyard: { sdr: 4, admin: 6 }, ridgeline: { admin: 1 } }, note: "Halyard archives a client's sequences when the client leaves." },
  { id: "seq.list.bulk", page: "sequences", area: "List", label: "Select several: pause, resume, archive", weekly: { sdr: 3, admin: 3 }, overrides: { halyard: { sdr: 3, admin: 8 }, fathom: { sdr: 1, admin: 2 } } },
  { id: "seq.list.archived", page: "sequences", area: "List", label: "Show archived sequences", weekly: { sdr: 2, admin: 3 }, overrides: { halyard: { admin: 4 } } },

  // Sequence header
  { id: "seq.page.counts", page: "sequences", area: "Sequence header", label: "People by status (active, paused, finished, replied, bounced, not sent)", weekly: { sdr: 85, ae: 25, admin: 22 }, overrides: { fathom: { sdr: 90, admin: 80 }, halyard: { sdr: 90, admin: 65 }, ridgeline: { sdr: 28, ae: 14, admin: 8 } } },
  { id: "seq.page.results", page: "sequences", area: "Sequence header", label: "Results strip (sent, delivered, opened, replied, interested, meetings)", weekly: { sdr: 25, ae: 10, admin: 20 }, overrides: { fathom: { sdr: 30, admin: 35 }, halyard: { sdr: 40, admin: 45 }, ridgeline: { sdr: 8, ae: 6, admin: 6 } }, note: "Counts and rates side by side; never a rate with the count on hover." },
  { id: "seq.page.health", page: "sequences", area: "Sequence header", label: "Bounce rate and bounce guard state", critical: true, weekly: { sdr: 20, ae: 4, admin: 35 }, overrides: { halyard: { sdr: 30, admin: 50 }, fathom: { sdr: 20, admin: 30 }, ridgeline: { sdr: 3, admin: 5 } }, note: "Safety state and the threshold that stops sending (rule 7)." },
  { id: "seq.page.status", page: "sequences", area: "Sequence header", label: "Pause or resume the sequence", weekly: { sdr: 30, ae: 6, admin: 10 }, overrides: { fathom: { sdr: 20, admin: 20 }, halyard: { sdr: 30, admin: 25 }, ridgeline: { sdr: 6, ae: 3, admin: 3 } }, note: "The consequence (people keep their place; nothing is deleted) is written next to the button." },
  { id: "seq.page.rename", page: "sequences", area: "Sequence header", label: "Rename", weekly: { sdr: 4, admin: 2 }, overrides: { halyard: { sdr: 6, admin: 8 } } },
  { id: "seq.page.owner", page: "sequences", area: "Sequence header", label: "Change owner", weekly: { sdr: 1, admin: 4 }, overrides: { fathom: { admin: 0 }, halyard: { admin: 6 } }, note: "Meridian reassigns when someone leaves; Halyard when a client moves between specialists. Removed at Fathom: nobody to hand to." },
  { id: "seq.page.share", page: "sequences", area: "Sequence header", label: "Who can see and edit", weekly: { sdr: 4, ae: 2, admin: 4 }, overrides: { fathom: { sdr: 0, admin: 0 }, halyard: { admin: 4 } }, note: "At Fathom everyone is an admin; the item is removed, not disabled." },
  { id: "seq.page.duplicate", page: "sequences", area: "Sequence header", label: "Duplicate (from the page)", weekly: { sdr: 3, ae: 1, admin: 3 }, overrides: { halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 1, admin: 1 } } },
  { id: "seq.page.archive", page: "sequences", area: "Sequence header", label: "Archive (from the page)", critical: true, weekly: { sdr: 3, admin: 4 }, overrides: { halyard: { sdr: 4, admin: 6 }, ridgeline: { admin: 1 } }, note: "The archive dialog states how many people stop and how many scheduled emails are deleted (rule 7)." },
  { id: "seq.page.delete-draft", page: "sequences", area: "Sequence header", label: "Delete draft", critical: true, weekly: { sdr: 2, admin: 1 }, overrides: { halyard: { sdr: 2, admin: 3 } }, note: "Only exists while the sequence is a draft with nobody in it; otherwise removed." },

  // Steps
  { id: "seq.steps.list", page: "sequences", area: "Steps", label: "Steps with per-step results", weekly: { sdr: 80, ae: 20, admin: 20 }, overrides: { fathom: { sdr: 85, admin: 80 }, halyard: { sdr: 85, admin: 60 }, ridgeline: { sdr: 22, ae: 10, admin: 6 } } },
  { id: "seq.steps.expand", page: "sequences", area: "Steps", label: "Open a step to read or edit it", weekly: { sdr: 40, ae: 8, admin: 8 }, overrides: { fathom: { sdr: 45, admin: 40 }, halyard: { sdr: 50, admin: 30 }, ridgeline: { sdr: 10, ae: 4, admin: 3 } } },
  { id: "seq.steps.edit-email", page: "sequences", area: "Steps", label: "Edit email subject and body", weekly: { sdr: 12, ae: 3, admin: 3 }, overrides: { fathom: { sdr: 20, admin: 22 }, halyard: { sdr: 20, admin: 12 }, ridgeline: { sdr: 5, ae: 2, admin: 1 } }, note: "Built once, run for months at Meridian; rewritten per client at Halyard; rewritten by the founder at Fathom." },
  { id: "seq.steps.variables", page: "sequences", area: "Steps", label: "Insert a variable (first name, company, signal)", weekly: { sdr: 6, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 12 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 2 } } },
  { id: "seq.steps.preview", page: "sequences", area: "Steps", label: "Preview a step for one person", weekly: { sdr: 8, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 12 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 3 } } },
  { id: "seq.steps.agent-draft", page: "sequences", area: "Steps", label: "Ask the outreach agent to draft the step", weekly: { sdr: 10, admin: 2 }, overrides: { fathom: { sdr: 30, admin: 30 }, halyard: { sdr: 10, admin: 5 }, ridgeline: { sdr: 3 } }, note: "Fathom has nobody with time to write; the agent drafts and a human approves." },
  { id: "seq.steps.variants", page: "sequences", area: "Steps", label: "A/B variants on an email step", weekly: { sdr: 4, admin: 2 }, overrides: { fathom: { sdr: 3, admin: 4 }, halyard: { sdr: 5, admin: 4 }, ridgeline: { sdr: 1 } } },
  { id: "seq.variant-progress", page: "sequences", area: "Steps", label: "Variant progress: how far the test has got, before any verdict", weekly: { sdr: 20, admin: 10 }, overrides: { fathom: { sdr: 35, admin: 25 }, halyard: { sdr: 30, admin: 25 }, ridgeline: { sdr: 4 } }, note: "\"A 96 of ~200 · B 91 of ~200 · not enough to call yet\". A results line without a sample size invites a decision the numbers do not support." },
  { id: "seq.promote-variant", page: "sequences", area: "Steps", label: "Promote a variant · turns the other off for everyone in this sequence", critical: true, weekly: { sdr: 12, admin: 6 }, overrides: { fathom: { sdr: 15, admin: 12 }, halyard: { sdr: 18, admin: 15 }, ridgeline: { sdr: 2 } }, note: "Changes what every person in the sequence receives from tomorrow, so the consequence is in the label and only the owner clicks it. An agent may propose a promotion and never make one." },
  { id: "seq.use-template", page: "sequences", area: "Steps", label: "Use a template, linked or copied, with what each choice means", weekly: { sdr: 30, ae: 10, admin: 15 }, overrides: { fathom: { sdr: 45, admin: 35 }, halyard: { sdr: 50, admin: 40 }, ridgeline: { sdr: 8, ae: 5, admin: 4 } }, note: "Inserts and closes like the variable menu. Link and Copy are named with their consequence (\"edits change this step everywhere it is used (4 steps today)\"), and a linked step prints a read-only line saying so." },
  { id: "seq.steps.linkedin-message", page: "sequences", area: "Steps", label: "The LinkedIn step's message text, with the variable menu", weekly: { sdr: 25, admin: 8 }, overrides: { fathom: { sdr: 30, admin: 25 }, halyard: { sdr: 35, admin: 20 }, ridgeline: { sdr: 4 } }, note: "Written once on the step and shown in tomorrow's task, instead of a note to self that leaves the copy to be written per contact." },
  { id: "seq.steps.add", page: "sequences", area: "Steps", label: "Add a step", weekly: { sdr: 8, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 12 }, ridgeline: { sdr: 2, admin: 1 } } },
  { id: "seq.steps.wait", page: "sequences", area: "Steps", label: "Change a wait", weekly: { sdr: 5, admin: 2 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 8, admin: 5 }, ridgeline: { sdr: 2 } } },
  { id: "seq.steps.reorder", page: "sequences", area: "Steps", label: "Reorder steps", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 }, fathom: { sdr: 4, admin: 4 } } },
  { id: "seq.steps.delete", page: "sequences", area: "Steps", label: "Delete a step", critical: true, weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 }, fathom: { sdr: 4, admin: 4 } }, note: "The dialog says how many people are waiting at the step and where they go next." },
  { id: "seq.steps.change-type", page: "sequences", area: "Steps", label: "Change a step's type", weekly: { sdr: 2, admin: 1 }, overrides: { halyard: { sdr: 2 } } },
  { id: "seq.steps.people-at-step", page: "sequences", area: "Steps", label: "Who is at this step now", weekly: { sdr: 6, ae: 2, admin: 2 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 8, admin: 4 }, ridgeline: { sdr: 2 } } },
  { id: "seq.steps.skip-toggle", page: "sequences", area: "Steps", label: "Turn a step off without deleting it", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 4, admin: 3 } }, note: "A step that is off is shown greyed with the word Off; the sequence never skips a step silently." },
  { id: "seq.steps.activate", page: "sequences", area: "Steps", label: "Activate a draft", weekly: { sdr: 6, ae: 2, admin: 2 }, overrides: { fathom: { sdr: 10, admin: 12 }, halyard: { sdr: 12, admin: 15 }, ridgeline: { sdr: 2, admin: 1 } } },
  { id: "seq.steps.expand-all", page: "sequences", area: "Steps", label: "Expand or collapse all steps", weekly: { sdr: 4, admin: 2 }, overrides: { halyard: { sdr: 6, admin: 4 }, fathom: { sdr: 6, admin: 6 } } },

  // People in the sequence
  { id: "seq.people.table", page: "sequences", area: "People", label: "People in the sequence with status and step", weekly: { sdr: 75, ae: 25, admin: 15 }, overrides: { fathom: { sdr: 80, admin: 75 }, halyard: { sdr: 85, admin: 55 }, ridgeline: { sdr: 25, ae: 14, admin: 5 } } },
  { id: "seq.people.filter-status", page: "sequences", area: "People", label: "Filter people by status", weekly: { sdr: 35, ae: 8, admin: 8 }, overrides: { fathom: { sdr: 30, admin: 25 }, halyard: { sdr: 40, admin: 25 }, ridgeline: { sdr: 10, ae: 4, admin: 2 } } },
  { id: "seq.people.search", page: "sequences", area: "People", label: "Find a person in the sequence", weekly: { sdr: 10, ae: 6, admin: 3 }, overrides: { fathom: { sdr: 8, admin: 8 }, halyard: { sdr: 10, admin: 4 }, ridgeline: { sdr: 4, ae: 3 } } },
  { id: "seq.mailbox-capacity", page: "sequences", area: "People", label: "Each mailbox's daily limit, sent today and sequences sharing it, in the picker", critical: true, weekly: { sdr: 55, ae: 15, admin: 30 }, overrides: { halyard: { sdr: 85, admin: 60 }, fathom: { sdr: 60, admin: 55 }, ridgeline: { sdr: 15, ae: 8, admin: 8 } }, note: "Choosing a mailbox is choosing capacity, and the names alone do not say so. The same block carries the day-one volume — \"212 added · 116 can send tomorrow from 2 mailboxes · the rest start Wednesday\" — because added and sent are different numbers." },
  { id: "seq.rotation-default", page: "sequences", area: "People", label: "The sequence's rotation default, named in the panel, changeable for this batch only", weekly: { sdr: 20, ae: 6, admin: 12 }, overrides: { halyard: { sdr: 45, admin: 35 }, fathom: { sdr: 15, admin: 15 }, ridgeline: { sdr: 3, admin: 2 } }, note: "One place holds the setting; the panel names it rather than offering the same choice a second time, and says that a change here applies to this batch only (rule 5)." },
  { id: "seq.people.add", page: "sequences", area: "People", label: "Add people", weekly: { sdr: 50, ae: 15, admin: 6 }, overrides: { fathom: { sdr: 60, admin: 55 }, halyard: { sdr: 65, admin: 35 }, ridgeline: { sdr: 20, ae: 12, admin: 3 } }, note: "Most enrolment happens from People and Lists; this is the second door in." },
  { id: "seq.people.open-reply", page: "sequences", area: "People", label: "Open the reply in Inbox", weekly: { sdr: 30, ae: 12, admin: 3 }, overrides: { fathom: { sdr: 35, admin: 30 }, halyard: { sdr: 40, admin: 12 }, ridgeline: { sdr: 12, ae: 8 } } },
  { id: "seq.people.pause-person", page: "sequences", area: "People", label: "Pause one person", weekly: { sdr: 12, ae: 6, admin: 2 }, overrides: { fathom: { sdr: 12, admin: 10 }, halyard: { sdr: 15, admin: 6 }, ridgeline: { sdr: 5, ae: 4 } } },
  { id: "seq.people.remove-person", page: "sequences", area: "People", label: "Remove one person", weekly: { sdr: 6, ae: 3, admin: 2 }, overrides: { halyard: { sdr: 8, admin: 4 }, ridgeline: { sdr: 3, ae: 2 } } },
  { id: "seq.people.finish-person", page: "sequences", area: "People", label: "Mark one person finished", weekly: { sdr: 5, ae: 3, admin: 1 }, overrides: { halyard: { sdr: 6, admin: 3 }, ridgeline: { sdr: 2 } } },
  { id: "seq.people.retry", page: "sequences", area: "People", label: "Fix the email and retry a not-sent person", weekly: { sdr: 8, admin: 5 }, overrides: { fathom: { sdr: 8, admin: 10 }, halyard: { sdr: 10, admin: 8 }, ridgeline: { sdr: 3 } } },
  { id: "seq.people.move-step", page: "sequences", area: "People", label: "Move a person to another step", weekly: { sdr: 3, admin: 1 }, overrides: { halyard: { sdr: 3 } } },
  { id: "seq.people.bulk", page: "sequences", area: "People", label: "Select several people: pause, resume, finish, remove", weekly: { sdr: 4, ae: 2, admin: 3 }, overrides: { fathom: { sdr: 5, admin: 6 }, halyard: { sdr: 6, admin: 6 }, ridgeline: { sdr: 2 } } },
  { id: "seq.people.export", page: "sequences", area: "People", label: "Export people (CSV)", weekly: { sdr: 2, admin: 3 }, overrides: { halyard: { admin: 4 } } },

  // Settings of this sequence
  { id: "seq.settings.mailbox", page: "sequences", area: "Settings", label: "Sending mailbox and today's limit", weekly: { sdr: 5, ae: 2, admin: 6 }, overrides: { fathom: { sdr: 8, admin: 10 }, halyard: { sdr: 20, admin: 22 }, ridgeline: { sdr: 2, admin: 2 } }, note: "Each Halyard client sends from its own mailboxes. The current value is always shown in the header; changing it is the door." },
  { id: "seq.settings.schedule", page: "sequences", area: "Settings", label: "Sending schedule", weekly: { sdr: 4, ae: 1, admin: 5 }, overrides: { fathom: { sdr: 4, admin: 5 }, halyard: { sdr: 10, admin: 10 }, ridgeline: { sdr: 2, admin: 2 } }, note: "Client time zones at Halyard. Schedules are defined in Settings; picked here." },
  { id: "seq.settings.ruleset", page: "sequences", area: "Settings", label: "Ruleset", weekly: { sdr: 3, admin: 5 }, overrides: { fathom: { sdr: 3, admin: 4 }, halyard: { sdr: 5, admin: 6 }, ridgeline: { admin: 1 } } },
  { id: "seq.settings.save-ruleset", page: "sequences", area: "Settings", label: "Save as a reusable ruleset · Growth", weekly: { sdr: 2, admin: 6 }, overrides: { halyard: { admin: 12, sdr: 4 }, fathom: { admin: 3 } }, note: "Gated at Growth and shown from the moment the sending-settings door opens, at the top of the ruleset block, with the plan name and the monthly total. The per-sequence rules underneath save normally on every plan: the lock is at the entry point, never after work the person cannot keep (gated features 7)." },
  { id: "seq.settings.priority", page: "sequences", area: "Settings", label: "Priority among sequences", weekly: { sdr: 3, admin: 2 }, overrides: { halyard: { sdr: 4, admin: 4 } } },
  { id: "seq.settings.daily-cap", page: "sequences", area: "Settings", label: "Emails per day from this sequence", weekly: { sdr: 3, admin: 4 }, overrides: { halyard: { sdr: 8, admin: 10 }, fathom: { sdr: 4, admin: 5 } }, note: "Shares the mailbox limit set in Settings; the two numbers are shown together (rule 5)." },
  { id: "seq.settings.tracking", page: "sequences", area: "Settings", label: "Open and click tracking for this sequence", weekly: { sdr: 2, admin: 2 } },

  // Templates (spec 05 §3.9): copy written once and used in many places
  { id: "tpl.list", page: "sequences", area: "Templates", label: "Templates table: name and folder, owner, last used, used by", weekly: { sdr: 25, ae: 10, marketer: 20, admin: 15 }, overrides: { halyard: { sdr: 40, admin: 30 }, fathom: { sdr: 30, admin: 25 }, ridgeline: { sdr: 6, ae: 5, marketer: 15, admin: 4 } }, note: "No profile puts Templates in the sidebar: it is reached from the step that uses it, from a campaign, from ⌘K and by deep link, and its header offers \"Add to sidebar\". Customer success does not hold it." },
  { id: "tpl.body", page: "sequences", area: "Templates", label: "Template body, variables and the snippets it nests", weekly: { sdr: 22, ae: 8, marketer: 18, admin: 12 }, overrides: { halyard: { sdr: 38, admin: 28 }, fathom: { sdr: 28, admin: 22 }, ridgeline: { sdr: 5, marketer: 12 } }, note: "Each nested snippet is named and linked rather than flattened, so a person editing here can see what is not theirs to change." },
  { id: "tpl.used-by", page: "sequences", area: "Templates", label: "Used by 4 steps and 1 campaign, as a section", critical: true, weekly: { sdr: 18, ae: 6, marketer: 15, admin: 12 }, overrides: { halyard: { sdr: 35, admin: 30 }, fathom: { sdr: 20, admin: 18 } }, note: "A person about to edit shared copy has to see who else receives the edit; that cannot sit behind a door (rule 5, rule 7)." },
  { id: "tpl.preview", page: "sequences", area: "Templates", label: "Preview on a real contact, naming the unfilled variables", weekly: { sdr: 20, ae: 8, marketer: 15, admin: 8 }, overrides: { halyard: { sdr: 32, admin: 20 }, fathom: { sdr: 25, admin: 18 } } },
  { id: "tpl.test-send", page: "sequences", area: "Templates", label: "Send a test to me", weekly: { sdr: 10, ae: 4, marketer: 8, admin: 6 }, overrides: { halyard: { sdr: 18, admin: 12 } } },
  { id: "tpl.archive", page: "sequences", area: "Templates", label: "Archive a template, stating what happens to the steps linked to it", weekly: { sdr: 3, ae: 1, marketer: 3, admin: 4 }, overrides: { halyard: { admin: 10 } } },

  // Results and history
  { id: "seq.results.by-step", page: "sequences", area: "Results", label: "Results by step and by audience", weekly: { sdr: 10, ae: 3, admin: 10 }, overrides: { fathom: { sdr: 10, admin: 15 }, halyard: { sdr: 15, admin: 25 }, ridgeline: { sdr: 4, admin: 3 } }, note: "Halyard reports results to clients weekly, so it is promoted for the ops lead." },
  { id: "seq.history", page: "sequences", area: "History", label: "Change history (edits, pauses, bounce guard events)", weekly: { sdr: 3, admin: 10 }, overrides: { halyard: { sdr: 4, admin: 15 }, fathom: { admin: 3 } } },
]
