import type { UsageItem } from "./model"

// Settings inventory: thirteen areas (PRODUCT.md, plus "How your team works" from the declared-sidebar decision of
// 14 Sep 2026, and the two the map added on 15 Sep: "Signals, scoring and personas" and "API, webhooks, MCP and CLI",
// IA-MAP 2.14). Baseline numbers describe Meridian Software.
// `ae_plus` is available on every item but used on none here: nothing in Settings differs for an AE with reports.
// Plan gating (PLAN.md, 13 Sep 2026): Fathom on Starter, Halyard and Ridgeline on Growth, Meridian on Scale.
// A gated item is visible where it would live with a lock and the plan name, never removed and never moved, and a
// lock does not change its number (gated-features pattern rules 1 and 9). 0 still means removed: the item does not
// exist for that business at any price.
// Halyard overrides: the agency switches between ten client workspaces daily, so workspace-level items are routine.
// Fathom overrides: everyone is an admin and the founders do outbound; only "sdr" and "admin" roles exist there.
// Ridgeline overrides: product-led, little outbound; sequences low, context and signals high.

const h = (admin: number, sdr?: number) => ({ halyard: { admin, ...(sdr !== undefined ? { sdr } : {}) } })

export const settingsItems: UsageItem[] = [
  // You (personal)
  { id: "me.notify-delivery", page: "settings", area: "You", label: "Where notifications go: digest or as they happen, Slack, push, mute, quiet hours", weekly: { admin: 4, sdr: 6, ae: 4, marketer: 3, cs: 3 }, overrides: { fathom: { admin: 8, sdr: 8 }, halyard: { admin: 6, sdr: 8 } }, note: "One row for delivery, because digest, channel, mute and quiet hours are read and changed together (rule 5). What you are notified about stays on the thing that notifies: Agents, Inbox, the CRM error log. This row is what the shell's notification panel links to." },

  { id: "me.mcp-token", page: "settings", area: "You", label: "Your MCP and CLI connections: client, authorised when, revoke", weekly: { admin: 4, sdr: 4, ae: 2, marketer: 2, cs: 2 }, overrides: { fathom: { admin: 8, sdr: 20 }, halyard: { admin: 5, sdr: 5 }, ridgeline: { admin: 3, sdr: 3 } }, note: "The personal half of `X-mcpscope` and `X-cliauth`: the workspace rows are the admin's, the token is yours, like a mailbox. Spec 17 owns the panels." },

  // Workspace
  { id: "ws.name", page: "settings", area: "Workspace", label: "Workspace name", weekly: { admin: 2 }, overrides: h(40), note: "Halyard renames and checks workspaces as clients come and go." },
  { id: "ws.logo", page: "settings", area: "Workspace", label: "Logo", weekly: { admin: 1 }, overrides: h(15) },
  { id: "ws.timezone", page: "settings", area: "Workspace", label: "Timezone", weekly: { admin: 3 }, overrides: h(35) },
  { id: "ws.currency", page: "settings", area: "Workspace", label: "Default currency", weekly: { admin: 2, ae: 1 }, overrides: h(25) },
  { id: "ws.language", page: "settings", area: "Workspace", label: "Language", weekly: { admin: 1 } },

  // How your team works (the declared sidebar: seat plus workspace profile, both declared, both editable here)
  { id: "work.profile", page: "settings", area: "How your team works", label: "Workspace profile and the three answers behind it", critical: true, weekly: { admin: 3 }, overrides: { halyard: { admin: 25 }, fathom: { admin: 2 }, ridgeline: { admin: 2 } }, note: "Declared at set-up (spec 16), never inferred. Halyard declares one per client workspace, so it is read most weeks." },
  { id: "work.seats", page: "settings", area: "How your team works", label: "Which seats exist in this workspace", critical: true, weekly: { admin: 8 }, overrides: { halyard: { admin: 20 }, fathom: { admin: 3 }, ridgeline: { admin: 4 } }, note: "The seat is declared at invite; this row says which of the five exist here, and the usage model returns zero for the rest." },
  { id: "work.left-out", page: "settings", area: "How your team works", label: "Pages the profile leaves out, with how many signals have arrived for each", weekly: { admin: 6 }, overrides: { halyard: { admin: 12 }, fathom: { admin: 10 }, ridgeline: { admin: 4 } }, note: "A left-out page still opens and still offers 'Add to sidebar'. The signal count is the input to the exposure rule, shown so nothing happens invisibly." },
  { id: "work.exposure", page: "settings", area: "How your team works", label: "Two-week exposure: which page is showing now, until when, and keep or drop it", weekly: { admin: 4 }, overrides: { halyard: { admin: 6 }, fathom: { admin: 9 }, ridgeline: { admin: 3 } }, note: "Hints do not teach; temporary exposure does (sweep 09). One exposure per period, and the answer is final until a new signal." },

  // Team and access
  { id: "team.users", page: "settings", area: "Team and access", label: "Users", weekly: { admin: 45 }, overrides: { halyard: { admin: 30 }, fathom: { admin: 6 } }, note: "At 300 people someone joins or leaves most weeks." },
  { id: "team.teams", page: "settings", area: "Team and access", label: "Teams", weekly: { admin: 10 }, overrides: { fathom: { admin: 1 } }, note: "Growth and Scale. Locked on Starter, so Fathom sees the row with the plan name and a price, not a gap." },
  { id: "team.profiles", page: "settings", area: "Team and access", label: "Permission profiles", weekly: { admin: 8 }, overrides: { fathom: { admin: 1 } }, note: "Growth and Scale; locked on Starter." },
  { id: "team.grants", page: "settings", area: "Team and access", label: "Additional grants on top of the profile", weekly: { admin: 8 }, overrides: { halyard: { admin: 12 }, fathom: { admin: 2 }, ridgeline: { admin: 5 } }, note: "Sits directly under the profile row with one line between them: 'Grants add to the profile. Prefer a grant to a new profile.' Without it the only way to give one person one extra thing is a profile of their own, which is how a hundred-profile workspace happens (19\u00a71.2, 19\u00a71.4)." },
  { id: "team.availability", page: "settings", area: "Team and access", label: "Available, or Away until a date", weekly: { admin: 12, sdr: 8, ae: 8, marketer: 6, cs: 6 }, overrides: { halyard: { admin: 20, sdr: 10 }, fathom: { admin: 6, sdr: 6 }, ridgeline: { admin: 8, sdr: 4, ae: 6, marketer: 5, cs: 5 } }, note: "Set by the person or the admin, and read by every routing rule (spec 19): a two-hour SLA lead handed to somebody on holiday is the 47-hour reply the rule exists to prevent." },
  { id: "team.viewas", page: "settings", area: "Team and access", label: "View as a teammate", weekly: { admin: 4 }, overrides: { halyard: { admin: 20 }, fathom: { admin: 1 }, ridgeline: { admin: 4 } }, note: "A mode on the page, not a panel: entered from a users-table row action or the area heading, it replaces the page with the teammate's own view under a persistent banner. A panel about what someone else sees, opened from inside another panel, was a level-2 node inside a level-2 node (IA-MAP convention 2). Growth: Starter has no permission profiles to preview, so the gated capability and the tool that verifies it are gated together." },
  { id: "team.offboarding", page: "settings", area: "Team and access", label: "Deactivate: reassign, unlink mailboxes, unmap from the CRM, then deactivate", critical: true, weekly: { admin: 8 }, overrides: { halyard: { admin: 20 }, fathom: { admin: 2 }, ridgeline: { admin: 4 } }, note: "Four ordered blocks, each with its count and its consequence in text. Open tasks move and paused or failed ones do not; 250 records a pass; until the CRM mapping is removed the person's activity keeps syncing; and the bill does not change until renewal (19\u00a71.8, 19\u00a71.9). Step four reads 'Reassign first' until the others are done or skipped with a reason." },
  { id: "sec.mfa", page: "settings", area: "Team and access", label: "Multi-factor authentication", weekly: { admin: 3 } },
  { id: "sec.sso", page: "settings", area: "Team and access", label: "Single sign-on", weekly: { admin: 2 }, overrides: { fathom: { admin: 1 } }, note: "Scale only, so it is locked at Fathom, Halyard and Ridgeline." },
  { id: "sec.ip", page: "settings", area: "Team and access", label: "IP allowlist", weekly: { admin: 1 }, note: "Scale only; locked everywhere but Meridian." },
  { id: "sec.password", page: "settings", area: "Team and access", label: "Password policy", weekly: { admin: 1 } },
  { id: "sec.session", page: "settings", area: "Team and access", label: "Session timeout", weekly: { admin: 1 } },

  // Email sending
  { id: "mail.mailboxes", page: "settings", area: "Email sending", label: "Mailboxes", weekly: { sdr: 60, ae: 25, admin: 40 }, overrides: { halyard: { admin: 70, sdr: 65 }, fathom: { admin: 50, sdr: 60 }, ridgeline: { sdr: 20, ae: 10, admin: 15 } }, note: "Deliverability score and sent-versus-limit are checked weekly by anyone sending volume." },
  { id: "mail.warmup", page: "settings", area: "Email sending", label: "Warm-up", weekly: { sdr: 30, admin: 25 }, overrides: { halyard: { admin: 55, sdr: 40 }, ridgeline: { sdr: 5, admin: 5 } } },
  { id: "mail.limits", page: "settings", area: "Email sending", label: "Daily, hourly and minimum delay between sends", weekly: { sdr: 20, admin: 30 }, overrides: { halyard: { admin: 50, sdr: 30 }, ridgeline: { sdr: 4, admin: 6 } } },
  { id: "mail.signature", page: "settings", area: "Email sending", label: "Email signature", weekly: { sdr: 5, ae: 5, marketer: 2, cs: 3, admin: 2 } },
  { id: "mail.domains", page: "settings", area: "Email sending", label: "Sending domains", critical: true, weekly: { admin: 20, sdr: 8 }, overrides: { halyard: { admin: 45, sdr: 12 }, fathom: { admin: 10, sdr: 8 }, ridgeline: { admin: 6, sdr: 3 } }, note: "The SDR seat reads this row and the domain panel \u2014 SPF, DKIM, DMARC and the bounce rate \u2014 with the editing controls absent and one line naming the admin. A rep whose sequence paused needs to know whether the domain is the reason (rule 7, and the first of the three kinds of 'cannot see it')." },
  { id: "mail.tracking-subdomain", page: "settings", area: "Email sending", label: "Tracking subdomain", weekly: { admin: 2 } },
  { id: "mail.bounce-guard", page: "settings", area: "Email sending", label: "Bounce guard: warns at 4%, pauses at 6%", critical: true, weekly: { admin: 35, sdr: 15 }, note: "The one pair for the whole product (PLAN.md, 14 Sep 2026), owned here and adjustable by the admin. Sequences, Campaigns, Reports, Agents, Home and the shell read these two numbers and show the observed rate beside them. An auto-pause threshold that stops sending is safety state (rule 7)." },
  { id: "mail.catch-all", page: "settings", area: "Email sending", label: "Block catch-all domains", weekly: { admin: 5 } },
  { id: "mail.unsubscribe-text", page: "settings", area: "Email sending", label: "Unsubscribe text", weekly: { admin: 3, sdr: 2 } },
  { id: "mail.unsubscribe-permission", page: "settings", area: "Email sending", label: "Users may disable the unsubscribe text", weekly: { admin: 2 }, note: "Depends on the unsubscribe text; never separated from it (rule 5)." },
  { id: "mail.tracking", page: "settings", area: "Email sending", label: "Open and click tracking", weekly: { sdr: 8, ae: 6, marketer: 10, admin: 4 } },

  // Prospecting rules
  { id: "pros.gdpr", page: "settings", area: "Prospecting rules", label: "GDPR restrictions by region", weekly: { admin: 4 }, note: "This row states the rule the rest of the product reads: a restricted person stays in every table and every count with the action replaced by one line \u2014 'Restricted: EU region rule \u00b7 Prospecting rules' \u2014 never removed, never blank, and agents log the same line as a skipped step. A silently shortened count is the worst version of a gap that does not explain itself." },
  { id: "pros.removal-list", page: "settings", area: "Prospecting rules", label: "Removal list: review, export, and delete everywhere", weekly: { admin: 5 }, overrides: { halyard: { admin: 3 }, fathom: { admin: 1 }, ridgeline: { admin: 2 } }, note: "A panel (`X-removal`) the map keeps and an earlier draft of this spec deleted; the map wins on node existence, and the monthly compliance sweep cannot be walked without it. Delete everywhere carries its whole consequence at level one inside the panel, with counts for records, CRM links, lists, sequences and jobs, and 'This cannot be undone'. Four lines answer the sweep in place: sequences, enrichment jobs, API keys with prospecting scope, and agents, each with a count and a link." },
  { id: "pros.dnc", page: "settings", area: "Prospecting rules", label: "Do-not-call screening: synchronised 2 September, next due 3 October", critical: true, weekly: { admin: 3 }, overrides: { halyard: { admin: 6 }, fathom: { admin: 2 }, ridgeline: { admin: 2 } }, note: "A 31-day clock, not a switch: the FTC requires synchronisation 'at least every 31 days', safe harbour requires access 'no more than 31 days before calling any consumer' and a record of the process kept for 24 months (19\u00a73.7). So the label carries the state, the row warns past 31 days, the review log lives in the row, and Home's health strip carries it the way it carries bounce guard. Critical, so it leaves the Prospecting door however low the number." },
  { id: "pros.primary-email", page: "settings", area: "Prospecting rules", label: "Primary email type", weekly: { admin: 2, sdr: 3 } },
  { id: "pros.duplicates", page: "settings", area: "Prospecting rules", label: "Duplicate handling, with the observed duplication rate beside the rule", weekly: { admin: 6 }, note: "3.1% against a target under 3%, shown the way bounce guard shows the observed rate beside its thresholds. A rule with no measurement beside it cannot be judged." },
  { id: "pros.in-progress", page: "settings", area: "Prospecting rules", label: "In-progress limit per account", weekly: { admin: 8, sdr: 6 } },
  { id: "pros.territories", page: "settings", area: "Prospecting rules", label: "Territories", weekly: { admin: 12 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 4 } }, note: "Growth and Scale; locked on Starter, so Fathom sees the row and its price." },

  // Pipeline and data
  { id: "pipe.stages", page: "settings", area: "Pipeline and data", label: "Pipelines and stages", weekly: { admin: 10, ae: 6 }, overrides: { fathom: { admin: 12 } } },
  { id: "pipe.contact-stages", page: "settings", area: "Pipeline and data", label: "Contact and account stages", weekly: { admin: 6 } },
  { id: "pipe.fields", page: "settings", area: "Pipeline and data", label: "Custom fields", weekly: { admin: 15, ae: 4, marketer: 4 } },
  { id: "pipe.currency", page: "settings", area: "Pipeline and data", label: "Deal currency", weekly: { admin: 2 } },
  { id: "pipe.enrichment-order", page: "settings", area: "Pipeline and data", label: "Enrichment provider order", weekly: { admin: 12, sdr: 4 }, overrides: { ridgeline: { admin: 5 } }, note: "Changed when credit spend spikes." },

  // Sequences
  { id: "pipe.required-at-stage", page: "settings", area: "Pipeline and data", label: "Required to enter a stage, per stage", weekly: { admin: 12, ae: 5 }, overrides: { fathom: { admin: 6 }, halyard: { admin: 5 }, ridgeline: { admin: 8, ae: 4 } }, note: "Set in the field panel and printed on the deal's stage stepper before the click, so a blocked move explains itself rather than failing." },
  { id: "pipe.deal-warnings", page: "settings", area: "Pipeline and data", label: "Deal warnings: the six, each with its threshold and the observed workspace value", weekly: { admin: 15, ae: 6 }, overrides: { fathom: { admin: 8 }, halyard: { admin: 6 }, ridgeline: { admin: 10, ae: 5 } }, note: "The thresholds the Deals board prints as chips. Threshold and observed value in one row, as bounce guard does." },
  { id: "pipe.forecast-categories", page: "settings", area: "Pipeline and data", label: "Forecast categories and what each one means", weekly: { admin: 10, ae: 4, cs: 3 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 4 }, ridgeline: { admin: 8, ae: 4, cs: 4 } }, note: "Five categories, owned here and read by Reports; the definition text is owned here too, and Reports prints it under each label rather than in a tooltip." },
  { id: "pipe.goal", page: "settings", area: "Pipeline and data", label: "Targets per period, per user and per team", weekly: { admin: 12, ae: 4, cs: 3 }, overrides: { fathom: { admin: 4 }, halyard: { admin: 6 }, ridgeline: { admin: 10, ae: 4, cs: 4 } }, note: "A goal is an attribute, not an object (IA-MAP 6.3): set here beside the forecast categories and shown as the denominator on the Forecast tab." },
  { id: "pipe.submission-window", page: "settings", area: "Pipeline and data", label: "Forecast submission day, time and window", weekly: { admin: 4, ae: 3, cs: 2 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 3 }, ridgeline: { admin: 4, ae: 3, cs: 3 } } },
  { id: "pipe.renewal-reminders", page: "settings", area: "Pipeline and data", label: "Renewal reminders: 120, 90, 60 and 30 days before the renewal date", weekly: { admin: 4, cs: 8 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 1 }, ridgeline: { admin: 4, cs: 15 } }, note: "Admin-set, one row. The reminder tasks are created for the account owner and land on Tasks, which is how a CS seat gets a renewal ladder without holding the Workflows page." },
  { id: "seq.schedules", page: "settings", area: "Sequences", label: "Sending schedules", weekly: { sdr: 12, admin: 8 }, overrides: { ridgeline: { sdr: 4, admin: 2 }, halyard: { sdr: 20, admin: 15 } } },
  { id: "seq.rulesets", page: "settings", area: "Sequences", label: "Sequence rulesets", weekly: { admin: 6, sdr: 4 }, overrides: { ridgeline: { admin: 1 } }, note: "Growth and above, and the position of the gate is the point: 'Save as a reusable ruleset \u00b7 Growth' is present, locked and priced at the top of the ruleset block from the moment the sequence sending door opens, before any field in it is touched. The per-sequence settings save normally underneath it. A lock on the Save button at the end of real work is drip pricing (gated-features pattern rule 7)." },
  { id: "seq.priority", page: "settings", area: "Sequences", label: "Sequence priority", weekly: { sdr: 3 } },

  // Agents and AI
  { id: "ai.context", page: "settings", area: "Agents and AI", label: "Company context", weekly: { marketer: 20, admin: 10 }, overrides: { ridgeline: { marketer: 30 }, fathom: { admin: 15 } } },
  { id: "ai.agents", page: "settings", area: "Agents and AI", label: "Agents on or off", weekly: { admin: 25, sdr: 10 }, overrides: { fathom: { admin: 40 } } },
  { id: "ai.approvals", page: "settings", area: "Agents and AI", label: "What agents may do without approval", critical: true, weekly: { admin: 30, sdr: 8 }, note: "Sending email and spending credits without a human is a consequence the admin must always see (rule 7)." },
  { id: "ai.credit-caps", page: "settings", area: "Agents and AI", label: "Agent credit caps", critical: true, weekly: { admin: 35 } },
  { id: "ai.second-approval", page: "settings", area: "Agents and AI", label: "Second approval above 1,000 recipients or 500 credits in one action", critical: true, weekly: { admin: 10, sdr: 4 }, overrides: { fathom: { admin: 4, sdr: 2 }, halyard: { admin: 12, sdr: 6 }, ridgeline: { admin: 5 } }, note: "The threshold an agent action must pass before an admin has to approve it as well as its owner (PLAN.md, 14 Sep 2026). Agents and Campaigns read it; neither sets it. A send limit is safety state (rule 7)." },
  { id: "ai.no-overwrite", page: "settings", area: "Agents and AI", label: "Agents never overwrite a field a person set or confirmed; they propose instead", critical: true, weekly: { admin: 10, sdr: 4, ae: 3, cs: 2, marketer: 2 }, overrides: { fathom: { admin: 12, sdr: 4 }, halyard: { admin: 10, sdr: 4 }, ridgeline: { admin: 8, marketer: 4 } }, note: "One line at level one beside the approval rules. It is what makes the suggested / edited / validated state chip on an agent-writable field mean anything." },
  { id: "ai.own-key", page: "settings", area: "Agents and AI", label: "Bring your own model key", weekly: { admin: 2 }, note: "Scale only; locked at Fathom, Halyard and Ridgeline." },

  // Signals, scoring and personas (S-scoring): the configuration behind agents that already score leads.
  // Seats OPS and MK, every plan. Three journeys of the marketer's and three of the CS and agent groups walk it.
  { id: "score.primary", page: "settings", area: "Signals, scoring and personas", label: "The primary score, its threshold, and the share of people above it", critical: true, weekly: { marketer: 55, admin: 30 }, overrides: { ridgeline: { marketer: 60, admin: 25 }, fathom: { admin: 8 }, halyard: { admin: 6 } }, note: "A threshold that routes people to a rep is a rule about other people's work, and the share above it is the one number that says whether it is doing any (17\u00a74: if 80% of the database scores above MQL, the threshold is not doing work)." },
  { id: "score.models", page: "settings", area: "Signals, scoring and personas", label: "Score models and their inputs", weekly: { marketer: 45, admin: 25 }, overrides: { ridgeline: { marketer: 50, admin: 22 }, fathom: { admin: 6 }, halyard: { admin: 5 } } },
  { id: "score.weights", page: "settings", area: "Signals, scoring and personas", label: "Weights and decay", weekly: { marketer: 15, admin: 10 }, overrides: { ridgeline: { marketer: 16, admin: 8 }, fathom: { admin: 4 }, halyard: { admin: 4 } }, note: "Decay is part of the model, not a separate setting: 30 days inactive reduces, 60 halves, 90 resets to the fit baseline (17\u00a74)." },
  { id: "score.preview", page: "settings", area: "Signals, scoring and personas", label: "Distribution preview: the share above the threshold, with its source beside it", weekly: { marketer: 18, admin: 12 }, overrides: { ridgeline: { marketer: 18, admin: 10 }, fathom: { admin: 4 }, halyard: { admin: 4 } }, note: "\"68% of people score above 62. Above 80% the threshold is not doing work (17\u00a74).\" The number and the standard it is judged against, together." },
  { id: "score.publish", page: "settings", area: "Signals, scoring and personas", label: "Publish a threshold: the old and new values, how many are above each today, and what happens to people already routed", critical: true, weekly: { marketer: 12, admin: 10 }, overrides: { ridgeline: { marketer: 12, admin: 8 }, fathom: { admin: 3 }, halyard: { admin: 3 } }, note: "The consequence above the button, and grandfathering as a radio pair with a count on each option. Publishing changes who gets contacted, which is rule 7's territory." },
  { id: "score.stamp", page: "settings", area: "Signals, scoring and personas", label: "Threshold n, published on a date by a person, shown beside the Score filter on People", weekly: { marketer: 12, admin: 8 }, overrides: { ridgeline: { marketer: 12, admin: 6 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Declared over inferred: a filter whose meaning changed silently last Tuesday is a filter nobody can trust." },
  { id: "score.personas", page: "settings", area: "Signals, scoring and personas", label: "Personas with their sizes", weekly: { marketer: 40, admin: 20 }, overrides: { ridgeline: { marketer: 35, admin: 16 }, fathom: { admin: 5 }, halyard: { admin: 4 } }, note: "Read by the People persona filter, the Find people control and the Campaign results persona door. One definition, three readers." },
  { id: "score.persona-def", page: "settings", area: "Signals, scoring and personas", label: "One persona: title, seniority, department, industry, size, geography", weekly: { marketer: 15, admin: 8 }, overrides: { ridgeline: { marketer: 14, admin: 6 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "score.signals", page: "settings", area: "Signals, scoring and personas", label: "Signals with their freshness", weekly: { marketer: 45, admin: 25 }, overrides: { ridgeline: { marketer: 60, admin: 25 }, fathom: { admin: 6 }, halyard: { admin: 5 } }, note: "A signal with no freshness beside it is a claim about now made from data about then." },
  { id: "score.signal-def", page: "settings", area: "Signals, scoring and personas", label: "One signal: definition, source, freshness, talking tips", weekly: { marketer: 15, admin: 10 }, overrides: { ridgeline: { marketer: 18, admin: 8 }, fathom: { admin: 4 }, halyard: { admin: 3 } } },
  { id: "score.expansion-routing", page: "settings", area: "Signals, scoring and personas", label: "Expansion routing: under $15,000 to the account owner, $25,000 and above to the account executive of record", critical: true, weekly: { marketer: 8, admin: 12, cs: 10 }, overrides: { ridgeline: { cs: 15, admin: 10, marketer: 6 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Declared over inferred, and decision-critical because it decides whose number an expansion lands on." },
  { id: "score.first-value", page: "settings", area: "Signals, scoring and personas", label: "The shipped signal: no first-value milestone in 90 days", weekly: { marketer: 4, admin: 4 , cs: 12 }, overrides: { ridgeline: { cs: 18, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Raises the Onboarding stalled risk on an account. The definition of first value is per workspace and lives with the signal, not on the account." },
  { id: "score.retired", page: "settings", area: "Signals, scoring and personas", label: "Retired signals, retired personas and archived models", weekly: { marketer: 8, admin: 4 }, overrides: { ridgeline: { marketer: 8, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "The area's one door, named by its contents with a count. A retired definition is kept because last quarter's numbers were computed with it." },

  // Integrations
  { id: "int.crm", page: "settings", area: "Integrations", label: "CRM sync", weekly: { admin: 40 }, overrides: { fathom: { admin: 5 }, halyard: { admin: 25 } } },
  { id: "int.field-mapping", page: "settings", area: "Integrations", label: "CRM field mapping", weekly: { admin: 15 }, overrides: { fathom: { admin: 2 } } },
  { id: "int.error-log", page: "settings", area: "Integrations", label: "Sync error log", weekly: { admin: 30 }, overrides: { fathom: { admin: 3 } } },
  { id: "int.calendar", page: "settings", area: "Integrations", label: "Calendar", weekly: { ae: 5, sdr: 5, cs: 4, admin: 3 } },
  { id: "int.slack", page: "settings", area: "Integrations", label: "Slack", weekly: { admin: 5 } },
  { id: "int.enrichment", page: "settings", area: "Integrations", label: "Enrichment provider", weekly: { admin: 6 } },

  // API, webhooks, MCP and CLI (S-developer): the thirteenth area, between Integrations and Plan.
  // `int.api-keys` and `int.webhooks` were moved here, not copied: Settings → Integrations door → API keys → a drawer
  // was three levels (rule 2), and the map created this area for exactly that reason (IA-MAP 2.14, gap 6.4f).
  // Spec 17 owns the four panels and the four surfaces; these are the rows on this page.
  { id: "dev.api-keys", page: "settings", area: "API, webhooks, MCP and CLI", label: "API keys: scope, last used, spend", weekly: { admin: 6 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 8 }, ridgeline: { admin: 4 } }, note: "Growth and above; on Starter the row sits where it always sits with the plan name and one total. Moved out of the Integrations door." },
  { id: "dev.webhooks", page: "settings", area: "API, webhooks, MCP and CLI", label: "Webhooks: events, delivery log, reconcile", weekly: { admin: 4 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 3 }, ridgeline: { admin: 12 } }, note: "Growth and above. Ridgeline is event-driven, so this is the row they read. Moved out of the Integrations door." },
  { id: "dev.mcp", page: "settings", area: "API, webhooks, MCP and CLI", label: "MCP connection and scope: read, safe writes, destructive writes", weekly: { admin: 12 }, overrides: { fathom: { admin: 25 }, halyard: { admin: 8 }, ridgeline: { admin: 6 } }, note: "Read scope is on every plan; the two write tiers ride the API entitlement at Growth and above (IA-MAP 6.4f). Gating the read scope would hide the product from the client the founders already work in, which is the discovery the gated-features pattern exists to protect." },
  { id: "dev.cli", page: "settings", area: "API, webhooks, MCP and CLI", label: "CLI device authorisations", weekly: { admin: 5 }, overrides: { halyard: { admin: 20 }, fathom: { admin: 8 }, ridgeline: { admin: 2 } }, note: "The agency's surface: ten workspaces, one loop, weekly." },
  { id: "dev.limits", page: "settings", area: "API, webhooks, MCP and CLI", label: "Limits are per workspace, not per key: 200 a minute, 6,000 an hour, 50,000 a day", critical: true, weekly: { admin: 5 }, overrides: { fathom: { admin: 3 }, halyard: { admin: 6 }, ridgeline: { admin: 4 } }, note: "Published where keys are made. A developer who does not know the limit is shared mints three keys and buys nothing (19\u00a79: 'Per team, not per API key or per user')." },
  { id: "dev.cost-table", page: "settings", area: "API, webhooks, MCP and CLI", label: "Published cost per endpoint: typical and maximum, with the waterfall tail", critical: true, weekly: { admin: 4 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 10 }, ridgeline: { admin: 3 } }, note: "The maximum, not the average: one phone waterfall reaches 45+ credits (19\u00a79), and an average hides a 45x outcome." },
  { id: "dev.hook-contract", page: "settings", area: "API, webhooks, MCP and CLI", label: "The delivery contract: at-least-once, signed, attempt-numbered, retried for 24 hours, never silently disabled, and the reconciliation endpoint", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 1 }, halyard: { admin: 2 }, ridgeline: { admin: 12 } }, note: "What a thing does to your data is never behind a door (rule 7). A developer who cannot read the contract builds the wrong handler and finds out by losing data (19\u00a710)." },
  { id: "dev.key-spend", page: "settings", area: "API, webhooks, MCP and CLI", label: "Spend per key, against the workspace balance", critical: true, weekly: { admin: 15 }, overrides: { fathom: { admin: 2 }, halyard: { admin: 20 }, ridgeline: { admin: 10 } } },
  { id: "dev.alert-80", page: "settings", area: "API, webhooks, MCP and CLI", label: "Alert the key's owner at 80% of the allocation", critical: true, weekly: { admin: 3 }, overrides: { fathom: { admin: 10 }, halyard: { admin: 8 }, ridgeline: { admin: 2 } }, note: "On by default; delivered as a digest line and a bell row under the existing 'credits low' kind. No new notification kind." },

  // Plan, billing and usage
  { id: "plan.seats", page: "settings", area: "Plan, billing and usage", label: "Plan and seats", weekly: { admin: 20 }, overrides: { halyard: { admin: 30 }, fathom: { admin: 15 } } },
  { id: "plan.price", page: "settings", area: "Plan, billing and usage", label: "Price and renewal date", critical: true, weekly: { admin: 25 } },
  { id: "plan.credits", page: "settings", area: "Plan, billing and usage", label: "Credit balance and burn rate", critical: true, weekly: { admin: 55, sdr: 30, ae: 15, marketer: 20, cs: 5 }, overrides: { fathom: { admin: 60, sdr: 40 } }, note: "The thing reviewers say surprises them at the end of the month." },
  { id: "plan.upgrade-requests", page: "settings", area: "Plan, billing and usage", label: "Upgrade requests from teammates", critical: true, weekly: { admin: 6 }, overrides: { fathom: { admin: 12 }, halyard: { admin: 10 }, ridgeline: { admin: 4 } }, note: "The strip keeps the line, the count and the cost and links into the Requests queue, which owns the review: two queues for one decision is how an approval gets missed (IA-MAP 2.11). Each request names the person, the feature, the plan, the monthly cost, where it came from and the reason they typed. The approver is making a price decision, so rule 7 applies to their screen too (gated-features pattern rule 5; Figma ships the same six fields). Highest at Fathom, where Starter locks the most." },
  { id: "plan.credit-breakdown", page: "settings", area: "Plan, billing and usage", label: "Credit spend by feature, by person and by surface", weekly: { admin: 30, sdr: 8 }, overrides: { fathom: { admin: 45, sdr: 12 }, halyard: { admin: 40, sdr: 10 }, ridgeline: { admin: 20, sdr: 4 } }, note: "One flat panel (`X-credits`), opened from the credits pill on its own channel, with three stacked ranked breakdowns \u2014 feature, person, and surface (app, automation, API, MCP, CLI, agents) \u2014 top five each and one 'show the rest'. Not three tabs: tabs hide what has to be compared. Every row links to the job, the person or the key behind it, and the footer names the cross-workspace route the app cannot give: 'Credits are per workspace. `ollopa credits --all-workspaces` reports across all ten.'" },
  { id: "plan.team-budget", page: "settings", area: "Plan, billing and usage", label: "Team credit budget", weekly: { admin: 12 }, overrides: { halyard: { admin: 20 }, fathom: { admin: 15 }, ridgeline: { admin: 6 } }, note: "Behind the Plan door everywhere except Halyard, where twenty puts it at level one." },
  { id: "plan.spike-alert", page: "settings", area: "Plan, billing and usage", label: "Credit spike alert: warn at n times the usual daily burn", critical: true, weekly: { admin: 10 }, overrides: { fathom: { admin: 20 }, halyard: { admin: 15 }, ridgeline: { admin: 5 } }, note: "The same object as bounce guard \u2014 a threshold that changes what the product does \u2014 so the pair sits at level one with the observed value beside it: 'Alert at 3\u00d7 \u00b7 today 1.1\u00d7 \u00b7 nothing alerted.'" },
  { id: "plan.invoices", page: "settings", area: "Plan, billing and usage", label: "Invoices", weekly: { admin: 8 } },
  { id: "plan.tax-id", page: "settings", area: "Plan, billing and usage", label: "Tax ID", weekly: { admin: 1 } },
  { id: "plan.cancel", page: "settings", area: "Plan, billing and usage", label: "Cancel plan", critical: true, weekly: { admin: 1 } },
  { id: "plan.export", page: "settings", area: "Plan, billing and usage", label: "Export all data", weekly: { admin: 2 } },
  { id: "plan.delete", page: "settings", area: "Plan, billing and usage", label: "Delete workspace", critical: true, weekly: { admin: 0.5 } },
]
