import type { UsageItem } from "./model"

// Workflows: the trigger-rule-action chains that route inbound work, and the run history that shows
// what they did. Nodes `P-workflows`, `R-workflow` and `D-wf-runs` (IA-MAP 2.11).
// Spec: specs/19-workflows.md.
//
// Seats: OPS and marketer (IA-MAP 2.11 and 6.4g). The marketer holds this page because routing MQLs and
// working inbound forms are the marketer's daily work; no SDR, AE or CS number exists, because a rep
// receives what a workflow produced and never opens the rule.
//
// Growth-gated, shown on Starter with a lock and the plan name at the entry point.
// Baseline describes Meridian, where routing new MQLs against a two-hour SLA is a daily duty.
// Ridgeline runs inbound forms rather than MQL routing, so the credit ceiling and the exception queue
// are what they read. Fathom is on Starter and has no marketer seat: the founder meets the page as a lock.
// Halyard routes nothing — outbound is run for clients — so the numbers there are the lock and little else.

export const workflowsItems: UsageItem[] = [
  // The workflow table
  { id: "wf.table", page: "workflows", area: "The workflow table", label: "Workflows: name, trigger, status, enrolled this week, credit ceiling and spend against it", weekly: { marketer: 55, admin: 35 }, overrides: { ridgeline: { marketer: 45, admin: 22 }, fathom: { admin: 3 }, halyard: { admin: 5 } }, note: "Which rule is firing, on whom, and what it is about to cost: the page's whole question, answered in the table." },
  { id: "wf.status", page: "workflows", area: "The workflow table", label: "On or off, who turned it off and when", critical: true, weekly: { marketer: 25, admin: 20 }, overrides: { ridgeline: { marketer: 22, admin: 20 }, fathom: { admin: 3 }, halyard: { admin: 4 } }, note: "A routing rule that is off is a queue filling up somewhere else; safety state, so level one whatever the number." },
  { id: "wf.lock", page: "workflows", area: "The workflow table", label: "On Starter: the page opens with its real shape and its real count, values withheld, the plan name and one total at the entry point", weekly: { marketer: 1, admin: 3 }, overrides: { ridgeline: { marketer: 1, admin: 3 }, fathom: { admin: 12 }, halyard: { admin: 3 } }, note: "Preview rather than an empty state (gated-features pattern rule 8), and the lock is at the entry point, never after a rule has been built (rule 7)." },
  { id: "wf.test", page: "workflows", area: "The workflow table", label: "Test this workflow on one record before turning it on", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.history", page: "workflows", area: "The workflow table", label: "What changed in this workflow, who changed it and when", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },

  // Trigger and enrolment
  { id: "wf.trigger", page: "workflows", area: "Trigger and enrolment", label: "The trigger: what starts this workflow", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "wf.enrolment", page: "workflows", area: "Trigger and enrolment", label: "Enrolment filters, and how many people match them now", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "wf.reenrol", page: "workflows", area: "Trigger and enrolment", label: "Whether the same person can be enrolled twice, and what happens when they are", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
  { id: "wf.limits", page: "workflows", area: "Trigger and enrolment", label: "Enrolment limits: how many a day, and what happens to the rest", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },

  // Rules and actions
  { id: "wf.rules", page: "workflows", area: "Rules and actions", label: "The rule rows: this condition, then this action", weekly: { marketer: 10, admin: 10 }, overrides: { ridgeline: { marketer: 10, admin: 12 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "wf.rule-owners", page: "workflows", area: "Rules and actions", label: "The routing rule in words: weighted round robin across n reps, m away until a date, skipped", critical: true, weekly: { marketer: 25, admin: 15 }, overrides: { ridgeline: { marketer: 12, admin: 10 }, fathom: { admin: 2 }, halyard: { admin: 3 } }, note: "Who is on the receiving end of an automatic action is part of the action (rule 7). Availability comes from the user's own Away-until date in Settings › Team and access, read by every routing rule; a two-hour SLA lead handed to somebody on holiday is the 47-hour reply this workflow exists to prevent." },
  { id: "wf.named-accounts", page: "workflows", area: "Rules and actions", label: "The named-account override, named in the rule row with its owner and its count", weekly: { marketer: 10, admin: 8 }, overrides: { ridgeline: { marketer: 6, admin: 6 }, fathom: { admin: 1 }, halyard: { admin: 2 } }, note: "Named, never opened by a marketer: territories are an admin area, and a seat gap is explained in place rather than routed through (the three kinds of 'cannot see it')." },
  { id: "wf.actions", page: "workflows", area: "Rules and actions", label: "What the rule does: create a task, assign an owner, add to a sequence, write a field, notify", weekly: { marketer: 8, admin: 8 }, overrides: { ridgeline: { marketer: 10, admin: 10 }, fathom: { admin: 3 }, halyard: { admin: 3 } } },
  { id: "wf.announce", page: "workflows", area: "Rules and actions", label: "A change other people feel writes one line into their Home strip and their next digest", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Not a tour, not a tooltip and not a modal: a fact in the place they already read facts, expiring after seven days or on first contact with the changed thing." },

  // The credit ceiling
  { id: "wf.ceiling", page: "workflows", area: "The credit ceiling", label: "The credit ceiling for this workflow, and what has been spent against it today", critical: true, weekly: { marketer: 25, admin: 25 }, overrides: { ridgeline: { marketer: 45, admin: 25 }, fathom: { admin: 3 }, halyard: { admin: 4 } }, note: "A cap is a fee and a commitment, so the observed spend sits beside the limit the way the bounce rate sits beside the guard (rule 7)." },
  { id: "wf.cap-behaviour", page: "workflows", area: "The credit ceiling", label: "At the ceiling: enrichment stops, people are still enrolled and routed, and 'Raise the ceiling' sits beside the line", critical: true, weekly: { marketer: 8, admin: 10 }, overrides: { ridgeline: { marketer: 28, admin: 18 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "No silent spend and no silent loss: the work is kept un-enriched and marked, never dropped." },

  // The SLA clock
  { id: "wf.sla-window", page: "workflows", area: "The SLA", label: "The response window per lead heat", critical: true, weekly: { marketer: 20, admin: 15 }, overrides: { ridgeline: { marketer: 12, admin: 8 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Sub-five-minute leads close at 32% against 12% (17§4, n=939), so the window is the number the page is built around." },
  { id: "wf.sla-running", page: "workflows", area: "The SLA", label: "How many are running against the clock right now", critical: true, weekly: { marketer: 50, admin: 25 }, overrides: { ridgeline: { marketer: 20, admin: 10 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.sla-breached", page: "workflows", area: "The SLA", label: "Breached today, each with its elapsed time in text", critical: true, weekly: { marketer: 45, admin: 25 }, overrides: { ridgeline: { marketer: 18, admin: 10 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Elapsed time in words and never colour alone (rule 4; WCAG)." },
  { id: "wf.sla-reassign", page: "workflows", area: "The SLA", label: "The reassignment rule in words: past the window, reassign to the next rep and tell the first", critical: true, weekly: { marketer: 12, admin: 10 }, overrides: { ridgeline: { marketer: 4, admin: 5 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },

  // Run history and exceptions (D-wf-runs)
  { id: "wf.runs", page: "workflows", area: "Run history and exceptions", label: "Run history and enrolment · n", weekly: { marketer: 30, admin: 25 }, overrides: { ridgeline: { marketer: 30, admin: 20 }, fathom: { admin: 3 }, halyard: { admin: 3 } }, note: "One door with two named sections inside it. The sections are not doors, so nothing here is three deep." },
  { id: "wf.enrolled", page: "workflows", area: "Run history and exceptions", label: "Enrolled (n): who, when, which rule matched, and what it created", weekly: { marketer: 18, admin: 15 }, overrides: { ridgeline: { marketer: 16, admin: 12 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.exceptions", page: "workflows", area: "Run history and exceptions", label: "Could not route (n): the reason on every row and the rule that produced it one link away", critical: true, weekly: { marketer: 30, admin: 25 }, overrides: { ridgeline: { marketer: 32, admin: 20 }, fathom: { admin: 2 }, halyard: { admin: 3 } }, note: "Routing exceptions are about records and stay here, where the rule is one click away; intake requests are about the workspace and stay on Requests (IA-MAP 6.4c)." },
  { id: "wf.run-task", page: "workflows", area: "Run history and exceptions", label: "The task a run created, and the rep it went to", weekly: { marketer: 18, admin: 10 }, overrides: { ridgeline: { marketer: 14, admin: 10 }, fathom: { admin: 2 }, halyard: { admin: 2 } }, note: "Opened from the run row on the record, not from inside the door: the marketer confirms the lead reached a rep without opening the rep's queue, which is an area the marketer's seat does not hold." },
  // The controls a real workflow builder accumulates: touched when a rule is built or when one misbehaves,
  // and almost never otherwise. They are the page's tail, and USAGE-MODEL.md says a page without one is
  // probably missing the settings a real product has.
  { id: "wf.branch", page: "workflows", area: "Rules and actions", label: "A branch: two paths from one condition", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.delay", page: "workflows", area: "Rules and actions", label: "A wait step, and what happens to people already waiting when the rule changes", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 2 } } },
  { id: "wf.exit", page: "workflows", area: "Rules and actions", label: "Exit criteria: what takes a person out before the end", weekly: { marketer: 6, admin: 6 }, overrides: { ridgeline: { marketer: 5, admin: 6 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.hours", page: "workflows", area: "Rules and actions", label: "Business hours: when actions may fire, and what the clock does overnight", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 2 } }, note: "Read with the SLA window, because a two-hour clock running at 23:00 is a breach nobody could have prevented." },
  { id: "wf.suppression", page: "workflows", area: "Rules and actions", label: "People this workflow never touches", weekly: { marketer: 5, admin: 6 }, overrides: { ridgeline: { marketer: 4, admin: 6 }, fathom: { admin: 1 }, halyard: { admin: 2 } } },
  { id: "wf.notify-step", page: "workflows", area: "Rules and actions", label: "A notify step: who is told, and where", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 2 } } },
  { id: "wf.owner", page: "workflows", area: "The workflow table", label: "Who owns this workflow, and who is told when it errors", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 4, admin: 4 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.folders", page: "workflows", area: "The workflow table", label: "Folders and search over the workflow list", weekly: { marketer: 4, admin: 4 }, overrides: { ridgeline: { marketer: 3, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
  { id: "wf.duplicate", page: "workflows", area: "The workflow table", label: "Duplicate a workflow, and what the copy does not carry", weekly: { marketer: 3, admin: 3 }, overrides: { ridgeline: { marketer: 3, admin: 3 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
  { id: "wf.archive", page: "workflows", area: "The workflow table", label: "Archive a workflow: what stops, and what is kept", weekly: { marketer: 2, admin: 3 }, overrides: { ridgeline: { marketer: 2, admin: 3 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
  { id: "wf.errors", page: "workflows", area: "Run history and exceptions", label: "Runs that errored: what failed, and why", weekly: { marketer: 12, admin: 15 }, overrides: { ridgeline: { marketer: 12, admin: 12 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.runs-filter", page: "workflows", area: "Run history and exceptions", label: "Filter the run history by rule, by rep or by reason", weekly: { marketer: 10, admin: 10 }, overrides: { ridgeline: { marketer: 10, admin: 8 }, fathom: { admin: 2 }, halyard: { admin: 2 } } },
  { id: "wf.runs-export", page: "workflows", area: "Run history and exceptions", label: "Export the run history", weekly: { marketer: 3, admin: 4 }, overrides: { ridgeline: { marketer: 3, admin: 4 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
  { id: "wf.runs-columns", page: "workflows", area: "Run history and exceptions", label: "Columns in the run history", weekly: { marketer: 2, admin: 3 }, overrides: { ridgeline: { marketer: 2, admin: 2 }, fathom: { admin: 1 }, halyard: { admin: 1 } } },
]
